#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_BIN="${SCRIPT_DIR}/accessd-connector"
if [[ ! -f "${SOURCE_BIN}" ]]; then
  SOURCE_BIN="${SCRIPT_DIR}/../accessd-connector"
fi
if [[ ! -f "${SOURCE_BIN}" ]]; then
  echo "[accessd-connector] binary not found next to installer"
  echo "Place this script beside accessd-connector and re-run."
  exit 1
fi

INSTALL_DIR="${ACCESSD_CONNECTOR_INSTALL_DIR:-${HOME}/.local/bin}"
CONFIG_DIR="${HOME}/.accessd-connector"
CONFIG_FILE="${CONFIG_DIR}/config.yaml"
ENV_DIR="${HOME}/.config/accessd"
ENV_FILE="${ENV_DIR}/connector.env"
HELPER_DIR="${CONFIG_DIR}/bin"
APP_DIR="${HOME}/Applications/AccessD Connector.app"
APP_CONTENTS="${APP_DIR}/Contents"
APP_MACOS="${APP_CONTENTS}/MacOS"
APP_PLIST="${APP_CONTENTS}/Info.plist"
LAUNCHER_SCRIPT="${HELPER_DIR}/url-handler-macos.sh"
TRUST_SCRIPT="${HELPER_DIR}/trust-refresh-macos.sh"
TARGET_BIN="${INSTALL_DIR}/accessd-connector"

has_tty() {
  [[ -t 0 && -t 1 ]]
}

trim() {
  local s="$1"
  s="${s#${s%%[![:space:]]*}}"
  s="${s%${s##*[![:space:]]}}"
  printf '%s' "$s"
}

origin_host() {
  local origin="$1"
  origin="$(trim "${origin}")"
  origin="${origin#http://}"
  origin="${origin#https://}"
  origin="${origin%%/*}"
  origin="${origin%%:*}"
  printf '%s' "${origin}"
}

pick_existing_path() {
  for candidate in "$@"; do
    [[ -z "${candidate}" ]] && continue
    if [[ -e "${candidate}" ]]; then
      printf '%s' "${candidate}"
      return 0
    fi
  done
  return 1
}

prompt_for_path_if_missing() {
  local label="$1"
  local current="$2"
  if [[ -n "${current}" ]]; then
    printf '%s' "${current}"
    return 0
  fi
  if ! has_tty; then
    printf ''
    return 0
  fi
  while true; do
    read -r -p "[accessd-connector] ${label} not detected. Enter full path or press Enter to skip: " input
    input="$(trim "${input}")"
    if [[ -z "${input}" ]]; then
      printf ''
      return 0
    fi
    if [[ -e "${input}" ]]; then
      printf '%s' "${input}"
      return 0
    fi
    echo "[accessd-connector] Path does not exist: ${input}"
  done
}

choose_terminal_pref() {
  local default="terminal"
  if [[ -d "/Applications/iTerm.app" || -d "${HOME}/Applications/iTerm.app" ]]; then
    default="iterm"
  fi
  if ! has_tty; then
    printf '%s' "${default}"
    return 0
  fi
  echo "[accessd-connector] Shell terminal preference"
  echo "  1) terminal (Apple Terminal)"
  echo "  2) iterm"
  read -r -p "Select terminal [1/2, default ${default}]: " choice
  choice="$(trim "${choice}")"
  case "${choice}" in
    2|iterm|iTerm|ITERM)
      printf 'iterm'
      ;;
    1|terminal|"")
      printf '%s' "${default}"
      ;;
    *)
      printf '%s' "${default}"
      ;;
  esac
}

write_installer_config() {
  local dbeaver_path="$1"
  local filezilla_path="$2"
  local redis_cli_path="$3"
  local terminal_pref="$4"

  local should_write="1"
  if [[ -f "${CONFIG_FILE}" ]]; then
    should_write="0"
    if has_tty; then
      read -r -p "[accessd-connector] Existing config found at ${CONFIG_FILE}. Replace with installer-detected paths? [y/N]: " replace_choice
      replace_choice="$(trim "${replace_choice}")"
      case "${replace_choice}" in
        y|Y|yes|YES)
          should_write="1"
          ;;
      esac
    fi
  fi

  if [[ "${should_write}" != "1" ]]; then
    echo "[accessd-connector] Keeping existing config: ${CONFIG_FILE}"
    return 0
  fi

  mkdir -p "${CONFIG_DIR}"
  {
    echo "# AccessD Connector config"
    echo "# Generated by installer"
    echo "apps:"
    if [[ -n "${dbeaver_path}" ]]; then
      echo "  dbeaver: \"${dbeaver_path}\""
    fi
    if [[ -n "${filezilla_path}" ]]; then
      echo "  filezilla: \"${filezilla_path}\""
    fi
    if [[ -n "${redis_cli_path}" ]]; then
      echo "  redis_cli: \"${redis_cli_path}\""
    fi
    echo ""
    echo "terminal:"
    echo "  macos: \"${terminal_pref}\""
  } > "${CONFIG_FILE}"
  chmod 0600 "${CONFIG_FILE}"
  echo "[accessd-connector] Wrote config: ${CONFIG_FILE}"
}

write_runtime_env_file() {
  local default_origin="${ACCESSD_CONNECTOR_ALLOWED_ORIGIN:-https://accessd.example.internal}"
  mkdir -p "${ENV_DIR}"
  if [[ -f "${ENV_FILE}" ]]; then
    echo "[accessd-connector] Keeping existing runtime env: ${ENV_FILE}"
    return 0
  fi

  {
    echo "# AccessD Connector runtime env (non-sensitive defaults)"
    echo "# Keep secrets out of this file."
    echo "ACCESSD_CONNECTOR_ADDR=127.0.0.1:9494"
    echo "ACCESSD_CONNECTOR_ALLOWED_ORIGIN=${default_origin}"
    echo "ACCESSD_CONNECTOR_ALLOW_ANY_ORIGIN=false"
    echo "ACCESSD_CONNECTOR_ALLOW_REMOTE=false"
    echo "ACCESSD_CONNECTOR_AUTO_TRUST_SERVER_CERT=true"
    echo "# ACCESSD_CONNECTOR_TRUST_CERT_URL=https://accessd.example.internal/downloads/certs/accessd-server.crt"
    echo ""
    echo "# Optional: set ACCESSD_CONNECTOR_SECRET in system environment"
    echo "# (recommended) instead of storing it here."
  } > "${ENV_FILE}"
  chmod 0600 "${ENV_FILE}"
  echo "[accessd-connector] Wrote runtime env: ${ENV_FILE}"
}

write_trust_refresh_script() {
  cat > "${TRUST_SCRIPT}" <<'TRUST'
#!/usr/bin/env bash
set -euo pipefail

trim() {
  local s="$1"
  s="${s#${s%%[![:space:]]*}}"
  s="${s%${s##*[![:space:]]}}"
  printf '%s' "$s"
}

origin_host() {
  local origin="$1"
  origin="$(trim "${origin}")"
  origin="${origin#http://}"
  origin="${origin#https://}"
  origin="${origin%%/*}"
  origin="${origin%%:*}"
  printf '%s' "${origin}"
}

ENV_FILE="${HOME}/.config/accessd/connector.env"
if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # shellcheck disable=SC1090
  . "${ENV_FILE}"
  set +a
fi

auto_trust="${ACCESSD_CONNECTOR_AUTO_TRUST_SERVER_CERT:-true}"
case "${auto_trust,,}" in
  0|false|no|off)
    exit 0
    ;;
esac

host="$(origin_host "${ACCESSD_CONNECTOR_ALLOWED_ORIGIN:-}")"
if [[ -z "${host}" || "${host}" == "localhost" || "${host}" == "127.0.0.1" || "${host}" == "accessd.example.internal" ]]; then
  exit 0
fi

cert_url="${ACCESSD_CONNECTOR_TRUST_CERT_URL:-https://${host}/downloads/certs/accessd-server.crt}"
cert_dir="${HOME}/.accessd-connector/certs"
cert_file="${cert_dir}/accessd-${host}.crt"
mkdir -p "${cert_dir}"

if ! command -v curl >/dev/null 2>&1; then
  exit 0
fi
if ! curl -fsS -k -L "${cert_url}" -o "${cert_file}"; then
  exit 0
fi

if command -v security >/dev/null 2>&1; then
  if command -v sudo >/dev/null 2>&1 && sudo -n true >/dev/null 2>&1; then
    sudo security add-trusted-cert -d -r trustAsRoot -k /Library/Keychains/System.keychain "${cert_file}" >/dev/null 2>&1 || true
    exit 0
  fi
  security add-trusted-cert -d -r trustRoot -k "${HOME}/Library/Keychains/login.keychain-db" "${cert_file}" >/dev/null 2>&1 || true
fi
TRUST
  chmod 0755 "${TRUST_SCRIPT}"
}

trust_accessd_server_cert() {
  if [[ -x "${TRUST_SCRIPT}" ]]; then
    "${TRUST_SCRIPT}" || true
  fi
}

is_connector_running() {
  if curl -fsS --max-time 1 "http://127.0.0.1:9494/version" >/dev/null 2>&1; then
    return 0
  fi
  if pgrep -x "accessd-connector" >/dev/null 2>&1; then
    return 0
  fi
  return 1
}

stop_running_connector() {
  if ! pgrep -x "accessd-connector" >/dev/null 2>&1; then
    return 0
  fi
  pkill -x "accessd-connector" >/dev/null 2>&1 || true
  for _ in {1..20}; do
    if ! pgrep -x "accessd-connector" >/dev/null 2>&1; then
      return 0
    fi
    sleep 0.2
  done
  return 1
}

start_connector() {
  if [[ -f "${ENV_FILE}" ]]; then
    set -a
    # shellcheck disable=SC1090
    . "${ENV_FILE}"
    set +a
  fi
  trust_accessd_server_cert
  nohup "${TARGET_BIN}" >/tmp/accessd-connector.out 2>/tmp/accessd-connector.err < /dev/null &
}

WAS_RUNNING="0"
if is_connector_running; then
  WAS_RUNNING="1"
  echo "[accessd-connector] Existing connector process detected. Stopping before reinstall..."
  if ! stop_running_connector; then
    echo "[accessd-connector] WARNING: connector process did not stop cleanly; continuing install."
  fi
fi

mkdir -p "${INSTALL_DIR}" "${HELPER_DIR}" "${APP_MACOS}"
install -m 0755 "${SOURCE_BIN}" "${TARGET_BIN}"
write_trust_refresh_script

cat > "${LAUNCHER_SCRIPT}" <<'LAUNCHER'
#!/usr/bin/env bash
set -euo pipefail

CONNECTOR_BIN="${HOME}/.local/bin/accessd-connector"
if [[ ! -x "${CONNECTOR_BIN}" ]]; then
  CONNECTOR_BIN="accessd-connector"
fi

ENV_FILE="${HOME}/.config/accessd/connector.env"
if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # shellcheck disable=SC1090
  . "${ENV_FILE}"
  set +a
fi

CONNECTOR_ADDR="${ACCESSD_CONNECTOR_ADDR:-127.0.0.1:9494}"
TRUST_SCRIPT="${HOME}/.accessd-connector/bin/trust-refresh-macos.sh"
if [[ -z "${ACCESSD_CONNECTOR_SECRET:-}" ]]; then
  echo "[accessd-connector] WARNING: ACCESSD_CONNECTOR_SECRET is not set in process env." >&2
fi
if [[ -x "${TRUST_SCRIPT}" ]]; then
  "${TRUST_SCRIPT}" || true
fi

if curl -fsS --max-time 1 "http://${CONNECTOR_ADDR}/version" >/dev/null 2>&1; then
  exit 0
fi

nohup "${CONNECTOR_BIN}" >/tmp/accessd-connector.out 2>/tmp/accessd-connector.err < /dev/null &
LAUNCHER
chmod 0755 "${LAUNCHER_SCRIPT}"

cat > "${APP_MACOS}/accessd-connector-url-handler" <<'APP'
#!/usr/bin/env bash
set -euo pipefail
"${HOME}/.accessd-connector/bin/url-handler-macos.sh" "$@"
APP
chmod 0755 "${APP_MACOS}/accessd-connector-url-handler"

cat > "${APP_PLIST}" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>CFBundleName</key>
    <string>AccessD Connector URL Handler</string>
    <key>CFBundleDisplayName</key>
    <string>AccessD Connector URL Handler</string>
    <key>CFBundleIdentifier</key>
    <string>co.districtd.accessd.connector.urlhandler</string>
    <key>CFBundleVersion</key>
    <string>1.0.0</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0.0</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleExecutable</key>
    <string>accessd-connector-url-handler</string>
    <key>LSMinimumSystemVersion</key>
    <string>10.14</string>
    <key>CFBundleURLTypes</key>
    <array>
      <dict>
        <key>CFBundleURLName</key>
        <string>AccessD Connector Protocol</string>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>accessd-connector</string>
        </array>
      </dict>
    </array>
  </dict>
</plist>
PLIST

open -Ra "${APP_DIR}" >/dev/null 2>&1 || true
open "${APP_DIR}" >/dev/null 2>&1 || true

if ! command -v accessd-connector >/dev/null 2>&1; then
  echo "[accessd-connector] Note: ${INSTALL_DIR} is not currently on PATH in this shell."
fi

dbeaver_detected="$(pick_existing_path \
  "/Applications/DBeaver.app" \
  "/Applications/DBeaverCE.app" \
  "/Applications/DBeaver Community.app" \
  "${HOME}/Applications/DBeaver.app" \
  "$(command -v dbeaver 2>/dev/null || true)" || true)"
filezilla_detected="$(pick_existing_path \
  "/Applications/FileZilla.app" \
  "/Applications/FileZilla.app/Contents/MacOS/filezilla" \
  "${HOME}/Applications/FileZilla.app" \
  "$(command -v filezilla 2>/dev/null || true)" || true)"
redis_detected="$(pick_existing_path "$(command -v redis-cli 2>/dev/null || true)" "/opt/homebrew/bin/redis-cli" "/usr/local/bin/redis-cli" || true)"

if ! command -v ssh >/dev/null 2>&1; then
  echo "[accessd-connector] WARNING: OpenSSH client (ssh) not detected. Shell launch will fail until installed."
fi

dbeaver_path="$(prompt_for_path_if_missing "DBeaver" "${dbeaver_detected}")"
filezilla_path="$(prompt_for_path_if_missing "FileZilla" "${filezilla_detected}")"
redis_cli_path="$(prompt_for_path_if_missing "redis-cli" "${redis_detected}")"
terminal_pref="$(choose_terminal_pref)"

write_installer_config "${dbeaver_path}" "${filezilla_path}" "${redis_cli_path}" "${terminal_pref}"
write_runtime_env_file
if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # shellcheck disable=SC1090
  . "${ENV_FILE}"
  set +a
fi
trust_accessd_server_cert

if [[ "${WAS_RUNNING}" == "1" ]]; then
  echo "[accessd-connector] Restarting connector after reinstall..."
  start_connector
fi

echo "[accessd-connector] Installed binary: ${TARGET_BIN}"
echo "[accessd-connector] Runtime env file: ${ENV_FILE}"
echo "[accessd-connector] Protocol handler app: ${APP_DIR}"
echo "[accessd-connector] Registered URL scheme: accessd-connector://"
echo "[accessd-connector] UI auto-start can now invoke accessd-connector://start"
