$ErrorActionPreference = 'Stop'

function Test-Interactive {
  $nonInteractive = $env:ACCESSD_CONNECTOR_INSTALLER_NONINTERACTIVE
  if (-not [string]::IsNullOrWhiteSpace($nonInteractive) -and $nonInteractive -match '^(?i:true|1|yes|on)$') {
    return $false
  }
  try {
    return [Environment]::UserInteractive
  } catch {
    return $false
  }
}

function Test-ReleasePayloadIntegrity {
  param([string]$ScriptDir)

  $verifyRaw = $env:ACCESSD_CONNECTOR_VERIFY_RELEASE
  if (-not [string]::IsNullOrWhiteSpace($verifyRaw) -and $verifyRaw -match '^(?i:false|0|no|off)$') {
    Write-Host "[accessd-connector] Skipping payload integrity verification (ACCESSD_CONNECTOR_VERIFY_RELEASE=$verifyRaw)."
    return
  }

  $allowRaw = $env:ACCESSD_CONNECTOR_ALLOW_UNVERIFIED_RELEASE
  $allowUnverified = -not [string]::IsNullOrWhiteSpace($allowRaw) -and $allowRaw -match '^(?i:true|1|yes|on)$'

  $checksFile = Join-Path $ScriptDir 'release-files-sha256.txt'
  if (-not (Test-Path $checksFile)) {
    $checksFile = Join-Path (Split-Path -Parent $ScriptDir) 'release-files-sha256.txt'
  }
  if (-not (Test-Path $checksFile)) {
    return
  }

  $baseDir = Split-Path -Parent $checksFile
  $failures = New-Object System.Collections.Generic.List[string]
  foreach ($line in Get-Content -Path $checksFile) {
    $trimmed = $line.Trim()
    if ([string]::IsNullOrWhiteSpace($trimmed)) { continue }
    $parts = $trimmed -split '\s+', 2
    if ($parts.Count -lt 2) { continue }
    $expected = $parts[0].Trim().ToLowerInvariant()
    $fileName = $parts[1].Trim()
    $target = Join-Path $baseDir $fileName
    if (-not (Test-Path $target)) {
      $failures.Add("missing file: $fileName")
      continue
    }
    try {
      $actual = (Get-FileHash -Algorithm SHA256 -Path $target).Hash.ToLowerInvariant()
    } catch {
      $failures.Add("failed hash read: $fileName")
      continue
    }
    if ($actual -ne $expected) {
      $failures.Add("checksum mismatch: $fileName")
    }
  }

  if ($failures.Count -eq 0) {
    Write-Host '[accessd-connector] Payload integrity check passed.'
    return
  }

  if ($allowUnverified) {
    Write-Host "[accessd-connector] WARNING: payload integrity issues detected but continuing due ACCESSD_CONNECTOR_ALLOW_UNVERIFIED_RELEASE=$allowRaw"
    foreach ($item in $failures) {
      Write-Host "[accessd-connector] WARNING: $item"
    }
    return
  }

  $msg = ($failures -join '; ')
  throw "[accessd-connector] payload integrity verification failed: $msg. Set ACCESSD_CONNECTOR_ALLOW_UNVERIFIED_RELEASE=true to bypass."
}

function Resolve-CandidatePath {
  param([string[]]$Candidates)
  foreach ($c in $Candidates) {
    if ([string]::IsNullOrWhiteSpace($c)) { continue }
    if (Test-Path $c) { return $c }
    try {
      $cmd = Get-Command $c -ErrorAction Stop
      if ($cmd -and $cmd.Source) { return $cmd.Source }
    } catch {
    }
  }
  return $null
}

function Prompt-PathIfMissing {
  param(
    [string]$Label,
    [string]$Current
  )
  if (-not [string]::IsNullOrWhiteSpace($Current)) { return $Current }
  if (-not (Test-Interactive)) { return $null }
  while ($true) {
    $inputPath = Read-Host "[accessd-connector] $Label not detected. Enter full path or press Enter to skip"
    if ([string]::IsNullOrWhiteSpace($inputPath)) { return $null }
    if (Test-Path $inputPath) { return $inputPath }
    Write-Host "[accessd-connector] Path does not exist: $inputPath"
  }
}

function Choose-TerminalPref {
  $default = 'cmd'
  $wt = Resolve-CandidatePath @('wt.exe', 'wt')
  if ($wt) { $default = 'wt' }
  if (-not (Test-Interactive)) { return $default }
  Write-Host '[accessd-connector] Shell terminal preference'
  Write-Host '  1) cmd'
  Write-Host '  2) powershell'
  Write-Host '  3) wt'
  $choice = Read-Host "Select terminal [1-3, default $default]"
  switch ($choice) {
    '2' { return 'powershell' }
    'powershell' { return 'powershell' }
    '3' { return 'wt' }
    'wt' { return 'wt' }
    default { return $default }
  }
}

function Write-InstallerConfig {
  param(
    [string]$ConfigFile,
    [string]$DBeaverPath,
    [string]$FileZillaPath,
    [string]$RedisCLIPath,
    [string]$PuTTYPath,
    [string]$WinSCPPath,
    [string]$TerminalPref
  )

  $shouldWrite = $true
  if (Test-Path $ConfigFile) {
    $shouldWrite = $false
    if (Test-Interactive) {
      $replaceChoice = Read-Host "[accessd-connector] Existing config found at $ConfigFile. Replace with installer-detected paths? [y/N]"
      if ($replaceChoice -match '^(?i:y|yes)$') {
        $shouldWrite = $true
      }
    }
  }

  if (-not $shouldWrite) {
    Write-Host "[accessd-connector] Keeping existing config: $ConfigFile"
    return
  }

  $configDir = Split-Path -Parent $ConfigFile
  New-Item -ItemType Directory -Force -Path $configDir | Out-Null

  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add('# AccessD Connector config')
  $lines.Add('# Generated by installer')
  $lines.Add('apps:')
  if ($DBeaverPath) { $lines.Add("  dbeaver: `"$DBeaverPath`"") }
  if ($FileZillaPath) { $lines.Add("  filezilla: `"$FileZillaPath`"") }
  if ($RedisCLIPath) { $lines.Add("  redis_cli: `"$RedisCLIPath`"") }
  if ($PuTTYPath) { $lines.Add("  putty: `"$PuTTYPath`"") }
  if ($WinSCPPath) { $lines.Add("  winscp: `"$WinSCPPath`"") }
  $lines.Add('')
  $lines.Add('terminal:')
  $lines.Add("  windows: `"$TerminalPref`"")

  Set-Content -Path $ConfigFile -Value $lines -Encoding UTF8
  Write-Host "[accessd-connector] Wrote config: $ConfigFile"
}

function Write-RuntimeEnvFile {
  param([string]$EnvFile)

  $envDir = Split-Path -Parent $EnvFile
  New-Item -ItemType Directory -Force -Path $envDir | Out-Null
  if (Test-Path $EnvFile) {
    Write-Host "[accessd-connector] Keeping existing runtime env: $EnvFile"
    Refresh-RuntimeEnvFile -EnvFile $EnvFile
    return
  }

  $defaultOrigin = if ([string]::IsNullOrWhiteSpace($env:ACCESSD_CONNECTOR_ALLOWED_ORIGIN)) {
    'https://accessd.example.internal'
  } else {
    $env:ACCESSD_CONNECTOR_ALLOWED_ORIGIN
  }

  $lines = @(
    '# AccessD Connector runtime env (non-sensitive defaults)'
    '# Keep secrets out of this file.'
    'ACCESSD_CONNECTOR_ADDR=127.0.0.1:9494'
    'ACCESSD_CONNECTOR_ENABLE_TLS=true'
    'ACCESSD_CONNECTOR_TLS_CERT_FILE=%USERPROFILE%/.accessd-connector/tls/localhost.crt'
    'ACCESSD_CONNECTOR_TLS_KEY_FILE=%USERPROFILE%/.accessd-connector/tls/localhost.key'
    "ACCESSD_CONNECTOR_ALLOWED_ORIGIN=$defaultOrigin"
    '# Optional backend online token verification endpoint.'
    '# If unset, connector derives: <allowed_origin>/api/connector/token/verify'
    '# ACCESSD_CONNECTOR_BACKEND_VERIFY_URL=https://accessd.example.internal/api/connector/token/verify'
    'ACCESSD_CONNECTOR_ALLOW_ANY_ORIGIN=false'
    'ACCESSD_CONNECTOR_ALLOW_REMOTE=false'
    '# Optional bootstrap env URL. Default if unset:'
    '# https://<ACCESSD_CONNECTOR_ALLOWED_ORIGIN host>/downloads/bootstrap/accessd-connector.env'
    '# ACCESSD_CONNECTOR_BOOTSTRAP_ENV_URL=https://accessd.example.internal/downloads/bootstrap/accessd-connector.env'
    'ACCESSD_CONNECTOR_AUTO_TRUST_SERVER_CERT=true'
    '# ACCESSD_CONNECTOR_TRUST_CERT_URL=https://accessd.example.internal/downloads/certs/accessd-server.crt'
    ''
    '# Optional legacy local-HMAC mode:'
    '# ACCESSD_CONNECTOR_SECRET=<shared-secret>'
  )
  Set-Content -Path $EnvFile -Value $lines -Encoding UTF8
  Write-Host "[accessd-connector] Wrote runtime env: $EnvFile"
}

function Get-EnvMapFromFile {
  param([string]$Path)
  $map = @{}
  if (-not (Test-Path $Path)) { return $map }
  foreach ($line in Get-Content -Path $Path) {
    $trimmed = $line.Trim()
    if ([string]::IsNullOrWhiteSpace($trimmed) -or $trimmed.StartsWith('#')) { continue }
    if ($trimmed -notmatch '^[A-Za-z_][A-Za-z0-9_]*=') { continue }
    $parts = $trimmed.Split('=', 2)
    if ($parts.Count -ne 2) { continue }
    $map[$parts[0].Trim()] = $parts[1].Trim()
  }
  return $map
}

function Expand-EnvValue {
  param([string]$Value)
  if ($null -eq $Value) { return $Value }
  $expanded = "$Value".Trim().Trim('"').Trim("'")
  if (-not [string]::IsNullOrWhiteSpace($env:USERPROFILE)) {
    $expanded = $expanded -replace '^\$HOME(?=[\\/]|$)', [Regex]::Escape($env:USERPROFILE).Replace('\\', '\')
    $expanded = $expanded -replace '^\$\{HOME\}(?=[\\/]|$)', [Regex]::Escape($env:USERPROFILE).Replace('\\', '\')
    $expanded = $expanded -replace '^%USERPROFILE%(?=[\\/]|$)', [Regex]::Escape($env:USERPROFILE).Replace('\\', '\')
  }
  if (-not [string]::IsNullOrWhiteSpace($env:LOCALAPPDATA)) {
    $expanded = $expanded -replace '^%LOCALAPPDATA%(?=[\\/]|$)', [Regex]::Escape($env:LOCALAPPDATA).Replace('\\', '\')
  }
  return $expanded
}

function Load-EnvFileIntoProcess {
  param([string]$Path)
  if (-not (Test-Path $Path)) { return }
  Get-Content -Path $Path | ForEach-Object {
    $line = ($_.Trim())
    if ([string]::IsNullOrWhiteSpace($line) -or $line.StartsWith('#')) { return }
    if ($line -notmatch '^[A-Za-z_][A-Za-z0-9_]*=') { return }
    $parts = $line.Split('=', 2)
    if ($parts.Count -ne 2) { return }
    $key = $parts[0].Trim()
    $value = Expand-EnvValue -Value $parts[1]
    [System.Environment]::SetEnvironmentVariable($key, $value, 'Process')
  }
}

function Import-CertificateToCurrentUserRoot {
  param(
    [string]$CertFile,
    [switch]$Quiet
  )
  if ([string]::IsNullOrWhiteSpace($CertFile) -or -not (Test-Path $CertFile)) { return $false }
  try {
    Import-Certificate -FilePath $CertFile -CertStoreLocation 'Cert:\CurrentUser\Root' | Out-Null
    return $true
  } catch {
  }
  try {
    & certutil.exe -user -f -addstore Root $CertFile *> $null
    if ($LASTEXITCODE -eq 0) {
      return $true
    }
  } catch {
  }
  if (-not $Quiet) {
    Write-Host "[accessd-connector] WARNING: failed to import cert into CurrentUser Root: $CertFile"
  }
  return $false
}

function Set-EnvValueInFile {
  param(
    [string]$Path,
    [string]$Key,
    [string]$Value
  )
  $lines = @()
  if (Test-Path $Path) {
    $lines = Get-Content -Path $Path
  }
  $updated = $false
  for ($i = 0; $i -lt $lines.Count; $i += 1) {
    $trimmed = $lines[$i].Trim()
    if ($trimmed.StartsWith('#')) { continue }
    if ($trimmed -match ("^{0}=" -f [Regex]::Escape($Key))) {
      $lines[$i] = "$Key=$Value"
      $updated = $true
      break
    }
  }
  if (-not $updated) {
    $lines += "$Key=$Value"
  }
  Set-Content -Path $Path -Value $lines -Encoding UTF8
}

function Test-PlaceholderValue {
  param([string]$Value)
  if ([string]::IsNullOrWhiteSpace($Value)) { return $true }
  return $Value -like '*accessd.example.internal*'
}

function Get-DerivedBackendVerifyURL {
  param([string]$Origin)
  if ([string]::IsNullOrWhiteSpace($Origin)) { return $null }
  $trimmed = $Origin.Trim().TrimEnd('/')
  return "$trimmed/api/connector/token/verify"
}

function Refresh-RuntimeEnvFile {
  param(
    [string]$EnvFile,
    [string]$SourceFile
  )
  if (-not (Test-Path $EnvFile)) { return }
  $current = Get-EnvMapFromFile -Path $EnvFile
  $source = @{}
  if (-not [string]::IsNullOrWhiteSpace($SourceFile) -and (Test-Path $SourceFile)) {
    $source = Get-EnvMapFromFile -Path $SourceFile
  }

  $existingOrigin = if ($current.ContainsKey('ACCESSD_CONNECTOR_ALLOWED_ORIGIN')) { "$($current['ACCESSD_CONNECTOR_ALLOWED_ORIGIN'])".Trim() } else { '' }
  $existingVerify = if ($current.ContainsKey('ACCESSD_CONNECTOR_BACKEND_VERIFY_URL')) { "$($current['ACCESSD_CONNECTOR_BACKEND_VERIFY_URL'])".Trim() } else { '' }
  $sourceOrigin = if ($source.ContainsKey('ACCESSD_CONNECTOR_ALLOWED_ORIGIN')) { "$($source['ACCESSD_CONNECTOR_ALLOWED_ORIGIN'])".Trim() } else { '' }
  $sourceVerify = if ($source.ContainsKey('ACCESSD_CONNECTOR_BACKEND_VERIFY_URL')) { "$($source['ACCESSD_CONNECTOR_BACKEND_VERIFY_URL'])".Trim() } else { '' }

  $desiredOrigin = $existingOrigin
  if (-not [string]::IsNullOrWhiteSpace($env:ACCESSD_CONNECTOR_ALLOWED_ORIGIN)) {
    $desiredOrigin = $env:ACCESSD_CONNECTOR_ALLOWED_ORIGIN.Trim()
  } elseif (Test-PlaceholderValue -Value $existingOrigin) {
    if (-not [string]::IsNullOrWhiteSpace($sourceOrigin)) {
      $desiredOrigin = $sourceOrigin
    }
  }
  if (-not [string]::IsNullOrWhiteSpace($desiredOrigin) -and $desiredOrigin -ne $existingOrigin) {
    Set-EnvValueInFile -Path $EnvFile -Key 'ACCESSD_CONNECTOR_ALLOWED_ORIGIN' -Value $desiredOrigin
    Write-Host "[accessd-connector] Updated ACCESSD_CONNECTOR_ALLOWED_ORIGIN in $EnvFile"
  }

  $desiredVerify = $existingVerify
  if (-not [string]::IsNullOrWhiteSpace($env:ACCESSD_CONNECTOR_BACKEND_VERIFY_URL)) {
    $desiredVerify = $env:ACCESSD_CONNECTOR_BACKEND_VERIFY_URL.Trim()
  } elseif (Test-PlaceholderValue -Value $existingVerify) {
    if (-not [string]::IsNullOrWhiteSpace($sourceVerify)) {
      $desiredVerify = $sourceVerify
    } elseif (-not [string]::IsNullOrWhiteSpace($desiredOrigin)) {
      $desiredVerify = Get-DerivedBackendVerifyURL -Origin $desiredOrigin
    }
  }
  if (-not [string]::IsNullOrWhiteSpace($desiredVerify) -and $desiredVerify -ne $existingVerify) {
    Set-EnvValueInFile -Path $EnvFile -Key 'ACCESSD_CONNECTOR_BACKEND_VERIFY_URL' -Value $desiredVerify
    Write-Host "[accessd-connector] Updated ACCESSD_CONNECTOR_BACKEND_VERIFY_URL in $EnvFile"
  }
}

function Download-EnvFileInsecure {
  param(
    [string]$Url,
    [string]$OutFile
  )
  $prev = [System.Net.ServicePointManager]::ServerCertificateValidationCallback
  try {
    [System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }
    $wc = New-Object System.Net.WebClient
    $wc.DownloadFile($Url, $OutFile)
    return $true
  } catch {
    return $false
  } finally {
    [System.Net.ServicePointManager]::ServerCertificateValidationCallback = $prev
  }
}

function Bootstrap-RuntimeEnvFile {
  param([string]$EnvFile)

  $origin = if ([string]::IsNullOrWhiteSpace($env:ACCESSD_CONNECTOR_ALLOWED_ORIGIN)) { 'https://accessd.example.internal' } else { $env:ACCESSD_CONNECTOR_ALLOWED_ORIGIN }
  $originHost = Get-OriginHost -Origin $origin
  if ([string]::IsNullOrWhiteSpace($originHost) -or $originHost -eq 'accessd.example.internal') { return }

  $envUrl = if ([string]::IsNullOrWhiteSpace($env:ACCESSD_CONNECTOR_BOOTSTRAP_ENV_URL)) {
    "https://$originHost/downloads/bootstrap/accessd-connector.env"
  } else {
    $env:ACCESSD_CONNECTOR_BOOTSTRAP_ENV_URL
  }

  $envDir = Split-Path -Parent $EnvFile
  New-Item -ItemType Directory -Force -Path $envDir | Out-Null
  $tmp = "$EnvFile.tmp"

  if (-not (Download-EnvFileInsecure -Url $envUrl -OutFile $tmp)) {
    Remove-Item -Force $tmp -ErrorAction SilentlyContinue
    return
  }
  if (-not (Select-String -Path $tmp -Pattern '^ACCESSD_CONNECTOR_ADDR=' -Quiet)) {
    Remove-Item -Force $tmp -ErrorAction SilentlyContinue
    return
  }
  if (Test-Path $EnvFile) {
    Refresh-RuntimeEnvFile -EnvFile $EnvFile -SourceFile $tmp
    Remove-Item -Force $tmp -ErrorAction SilentlyContinue
    return
  }
  Move-Item -Force $tmp $EnvFile
  Write-Host "[accessd-connector] Downloaded runtime env from $envUrl"
}

function Get-OriginHost {
  param([string]$Origin)
  if ([string]::IsNullOrWhiteSpace($Origin)) { return $null }
  try {
    return ([Uri]$Origin).Host
  } catch {
    return $null
  }
}

function Save-RemoteServerCert {
  param(
    [string]$ServerHost,
    [string]$OutFile
  )
  $tcp = $null
  $ssl = $null
  try {
    $tcp = New-Object System.Net.Sockets.TcpClient($ServerHost, 443)
    $ssl = New-Object System.Net.Security.SslStream($tcp.GetStream(), $false, ({ $true }))
    $ssl.AuthenticateAsClient($ServerHost)
    $remote = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2($ssl.RemoteCertificate)
    [System.IO.File]::WriteAllBytes($OutFile, $remote.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Cert))
    return $true
  } catch {
    return $false
  } finally {
    if ($ssl) { $ssl.Dispose() }
    if ($tcp) { $tcp.Close() }
  }
}

function Trust-AccessDServerCert {
  param([string]$RuntimeEnvFile)

  $autoTrust = $env:ACCESSD_CONNECTOR_AUTO_TRUST_SERVER_CERT
  if (-not [string]::IsNullOrWhiteSpace($autoTrust) -and $autoTrust -match '^(?i:false|0|no|off)$') {
    Write-Host "[accessd-connector] Auto trust disabled (ACCESSD_CONNECTOR_AUTO_TRUST_SERVER_CERT=$autoTrust)."
    return
  }

  $origin = $env:ACCESSD_CONNECTOR_ALLOWED_ORIGIN
  $originHost = Get-OriginHost -Origin $origin
  if ([string]::IsNullOrWhiteSpace($originHost) -or $originHost -in @('localhost', '127.0.0.1', 'accessd.example.internal')) {
    return
  }

  $certDir = Join-Path $configDir 'certs'
  New-Item -ItemType Directory -Force -Path $certDir | Out-Null
  $certFile = Join-Path $certDir ("accessd-{0}.cer" -f $originHost)
  $stateFile = Join-Path $certDir ("accessd-{0}.trusted.sha256" -f $originHost)

  $saved = Save-RemoteServerCert -ServerHost $originHost -OutFile $certFile
  if (-not $saved) {
    Write-Host "[accessd-connector] WARNING: failed to fetch TLS certificate from $originHost:443"
    return
  }

  $certHash = $null
  try {
    $certHash = (Get-FileHash -Algorithm SHA256 -Path $certFile).Hash.ToLowerInvariant()
  } catch {
    $certHash = $null
  }
  if ($certHash -and (Test-Path $stateFile)) {
    try {
      $existingHash = (Get-Content -Path $stateFile -Raw).Trim().ToLowerInvariant()
      if ($existingHash -eq $certHash) {
        return
      }
    } catch {
    }
  }

  try {
    if (Import-CertificateToCurrentUserRoot -CertFile $certFile -Quiet) {
      Write-Host "[accessd-connector] Installed server cert into CurrentUser Root trust store: $certFile"
      if ($certHash) {
        Set-Content -Path $stateFile -Value $certHash -Encoding ASCII
      }
      return
    }
    Write-Host "[accessd-connector] Saved cert at: $certFile"
  } catch {
    Write-Host "[accessd-connector] WARNING: failed to trust server cert: $($_.Exception.Message)"
  }
}

function Trust-LocalConnectorTLSCert {
  param([string]$ConnectorBinary)
  if (-not (Test-Path $ConnectorBinary)) { return }
  $certFile = $null
  try {
    $certFile = (& $ConnectorBinary ensure-local-tls 2>$null | Select-Object -First 1)
  } catch {
    return
  }
  if ([string]::IsNullOrWhiteSpace($certFile)) { return }
  $certPath = "$certFile".Trim()
  if (-not (Test-Path $certPath)) { return }
  if (-not (Import-CertificateToCurrentUserRoot -CertFile $certPath -Quiet)) {
    Write-Host "[accessd-connector] WARNING: failed to trust local connector TLS cert: $certPath"
  }
}

function Start-ConnectorProcess {
  param(
    [string]$BinaryPath,
    [string]$RuntimeEnvFile,
    [string]$Reason
  )
  if (-not (Test-Path $BinaryPath)) { return $false }
  try {
    $alreadyRunning = Get-Process -Name 'accessd-connector' -ErrorAction SilentlyContinue
    if ($alreadyRunning) {
      return $true
    }
    Load-EnvFileIntoProcess -Path $RuntimeEnvFile
    Start-Process -FilePath $BinaryPath -WindowStyle Hidden | Out-Null
    if ([string]::IsNullOrWhiteSpace($Reason)) {
      Write-Host '[accessd-connector] Started connector process.'
    } else {
      Write-Host "[accessd-connector] Started connector process ($Reason)."
    }
    return $true
  } catch {
    Write-Host "[accessd-connector] WARNING: failed to start connector automatically: $($_.Exception.Message)"
    return $false
  }
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Test-ReleasePayloadIntegrity -ScriptDir $scriptDir
$sourceBin = Join-Path $scriptDir 'accessd-connector.exe'
if (-not (Test-Path $sourceBin)) {
  $sourceBin = Join-Path (Split-Path -Parent $scriptDir) 'accessd-connector.exe'
}
if (-not (Test-Path $sourceBin)) {
  throw "[accessd-connector] accessd-connector.exe not found next to installer"
}

$installDir = if ($env:ACCESSD_CONNECTOR_INSTALL_DIR) { $env:ACCESSD_CONNECTOR_INSTALL_DIR } else { Join-Path $env:LOCALAPPDATA 'AccessD\\bin' }
$configDir = Join-Path $env:USERPROFILE '.accessd-connector'
$configFile = Join-Path $configDir 'config.yaml'
$helperDir = Join-Path $configDir 'bin'
$runtimeEnvFile = Join-Path (Join-Path $env:USERPROFILE '.config\accessd') 'connector.env'
$targetBin = Join-Path $installDir 'accessd-connector.exe'
$handlerScript = Join-Path $helperDir 'url-handler-windows.ps1'
$trustHelperScript = Join-Path $helperDir 'trust-refresh-windows.ps1'

New-Item -ItemType Directory -Force -Path $installDir | Out-Null
New-Item -ItemType Directory -Force -Path $helperDir | Out-Null

$wasRunning = $false
try {
  $running = Get-Process -Name 'accessd-connector' -ErrorAction SilentlyContinue
  if ($running) {
    $wasRunning = $true
    Write-Host '[accessd-connector] Existing connector process detected. Stopping before reinstall...'
    $running | Stop-Process -Force -ErrorAction SilentlyContinue
    Start-Sleep -Milliseconds 600
  }
} catch {
}

$sourceResolved = [System.IO.Path]::GetFullPath($sourceBin)
$targetResolved = [System.IO.Path]::GetFullPath($targetBin)
if ($sourceResolved -ieq $targetResolved) {
  Write-Host "[accessd-connector] Source and target binary paths are identical; skipping copy."
} else {
  Copy-Item -Force $sourceBin $targetBin
}

@"
`$ErrorActionPreference = 'SilentlyContinue'
function Expand-EnvValue {
  param([string]`$Value)
  if (`$null -eq `$Value) { return `$Value }
  `$expanded = "`$Value".Trim().Trim('"').Trim("'")
  if (-not [string]::IsNullOrWhiteSpace(`$env:USERPROFILE)) {
    `$expanded = `$expanded -replace '^\$HOME(?=[\\/]|$)', [Regex]::Escape(`$env:USERPROFILE).Replace('\\', '\')
    `$expanded = `$expanded -replace '^\$\{HOME\}(?=[\\/]|$)', [Regex]::Escape(`$env:USERPROFILE).Replace('\\', '\')
    `$expanded = `$expanded -replace '^%USERPROFILE%(?=[\\/]|$)', [Regex]::Escape(`$env:USERPROFILE).Replace('\\', '\')
  }
  return `$expanded
}
function Get-OriginHost {
  param([string]`$Origin)
  if ([string]::IsNullOrWhiteSpace(`$Origin)) { return `$null }
  try { return ([Uri]`$Origin).Host } catch { return `$null }
}
function Save-RemoteServerCert {
  param([string]`$ServerHost, [string]`$OutFile)
  `$tcp = `$null
  `$ssl = `$null
  try {
    `$tcp = New-Object System.Net.Sockets.TcpClient(`$ServerHost, 443)
    `$ssl = New-Object System.Net.Security.SslStream(`$tcp.GetStream(), `$false, ({ `$true }))
    `$ssl.AuthenticateAsClient(`$ServerHost)
    `$remote = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2(`$ssl.RemoteCertificate)
    [System.IO.File]::WriteAllBytes(`$OutFile, `$remote.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Cert))
    return `$true
  } catch {
    return `$false
  } finally {
    if (`$ssl) { `$ssl.Dispose() }
    if (`$tcp) { `$tcp.Close() }
  }
}
`$envFile = Join-Path `$env:USERPROFILE '.config\accessd\connector.env'
if (Test-Path `$envFile) {
  Get-Content `$envFile | ForEach-Object {
    `$line = (`$_.Trim())
    if ([string]::IsNullOrWhiteSpace(`$line) -or `$line.StartsWith('#')) { return }
    if (`$line -notmatch '^[A-Za-z_][A-Za-z0-9_]*=') { return }
    `$parts = `$line.Split('=', 2)
    if (`$parts.Count -ne 2) { return }
    `$key = `$parts[0].Trim()
    `$value = Expand-EnvValue -Value `$parts[1]
    [System.Environment]::SetEnvironmentVariable(`$key, `$value, 'Process')
  }
}
`$autoTrust = `$env:ACCESSD_CONNECTOR_AUTO_TRUST_SERVER_CERT
if (-not [string]::IsNullOrWhiteSpace(`$autoTrust) -and `$autoTrust -match '^(?i:false|0|no|off)$') { exit 0 }
`$originHost = Get-OriginHost -Origin `$env:ACCESSD_CONNECTOR_ALLOWED_ORIGIN
if ([string]::IsNullOrWhiteSpace(`$originHost) -or `$originHost -in @('localhost', '127.0.0.1', 'accessd.example.internal')) { exit 0 }
`$certDir = Join-Path `$env:USERPROFILE '.accessd-connector\certs'
New-Item -ItemType Directory -Force -Path `$certDir | Out-Null
`$certFile = Join-Path `$certDir ("accessd-{0}.cer" -f `$originHost)
if (-not (Save-RemoteServerCert -ServerHost `$originHost -OutFile `$certFile)) { exit 0 }
try {
  Import-Certificate -FilePath `$certFile -CertStoreLocation 'Cert:\CurrentUser\Root' | Out-Null
} catch {
  & certutil.exe -user -f -addstore Root `$certFile *> `$null
}
"@ | Set-Content -Path $trustHelperScript -Encoding UTF8

@"
`$ErrorActionPreference = 'SilentlyContinue'
$envFile = Join-Path `$env:USERPROFILE '.config\accessd\connector.env'
function Expand-EnvValue {
  param([string]`$Value)
  if (`$null -eq `$Value) { return `$Value }
  `$expanded = "`$Value".Trim().Trim('"').Trim("'")
  if (-not [string]::IsNullOrWhiteSpace(`$env:USERPROFILE)) {
    `$expanded = `$expanded -replace '^\$HOME(?=[\\/]|$)', [Regex]::Escape(`$env:USERPROFILE).Replace('\\', '\')
    `$expanded = `$expanded -replace '^\$\{HOME\}(?=[\\/]|$)', [Regex]::Escape(`$env:USERPROFILE).Replace('\\', '\')
    `$expanded = `$expanded -replace '^%USERPROFILE%(?=[\\/]|$)', [Regex]::Escape(`$env:USERPROFILE).Replace('\\', '\')
  }
  if (-not [string]::IsNullOrWhiteSpace(`$env:LOCALAPPDATA)) {
    `$expanded = `$expanded -replace '^%LOCALAPPDATA%(?=[\\/]|$)', [Regex]::Escape(`$env:LOCALAPPDATA).Replace('\\', '\')
  }
  return `$expanded
}
function Get-OriginFromProtocolArg {
  param([string]`$Arg)
  if ([string]::IsNullOrWhiteSpace(`$Arg)) { return `$null }
  if (-not `$Arg.StartsWith('accessd-connector://')) { return `$null }
  try {
    `$uri = [Uri]`$Arg
  } catch {
    return `$null
  }
  `$query = `$uri.Query
  if ([string]::IsNullOrWhiteSpace(`$query)) { return `$null }
  `$trimmed = `$query.TrimStart('?')
  foreach (`$part in `$trimmed.Split('&')) {
    if ([string]::IsNullOrWhiteSpace(`$part)) { continue }
    `$kv = `$part.Split('=', 2)
    if (`$kv.Count -ne 2) { continue }
    if (`$kv[0] -ne 'origin') { continue }
    try {
      `$decoded = [Uri]::UnescapeDataString(`$kv[1])
    } catch {
      `$decoded = `$kv[1]
    }
    if (`$decoded -like 'http://*' -or `$decoded -like 'https://*') {
      return `$decoded.TrimEnd('/')
    }
    return `$null
  }
  return `$null
}
function Get-QueryParamFromProtocolArg {
  param([string]`$Arg, [string]`$Name)
  if ([string]::IsNullOrWhiteSpace(`$Arg) -or [string]::IsNullOrWhiteSpace(`$Name)) { return `$null }
  if (-not `$Arg.StartsWith('accessd-connector://')) { return `$null }
  try { `$uri = [Uri]`$Arg } catch { return `$null }
  `$query = `$uri.Query
  if ([string]::IsNullOrWhiteSpace(`$query)) { return `$null }
  `$trimmed = `$query.TrimStart('?')
  foreach (`$part in `$trimmed.Split('&')) {
    if ([string]::IsNullOrWhiteSpace(`$part)) { continue }
    `$kv = `$part.Split('=', 2)
    if (`$kv.Count -ne 2) { continue }
    if (`$kv[0] -ne `$Name) { continue }
    try { return [Uri]::UnescapeDataString(`$kv[1]) } catch { return `$kv[1] }
  }
  return `$null
}
function Set-EnvValueInFile {
  param([string]`$Path, [string]`$Key, [string]`$Value)
  `$lines = @()
  if (Test-Path `$Path) { `$lines = Get-Content -Path `$Path }
  `$updated = `$false
  for (`$i = 0; `$i -lt `$lines.Count; `$i += 1) {
    `$trimmed = `$lines[`$i].Trim()
    if (`$trimmed.StartsWith('#')) { continue }
    if (`$trimmed -match ("^{0}=" -f [Regex]::Escape(`$Key))) {
      `$lines[`$i] = "`$Key=`$Value"
      `$updated = `$true
      break
    }
  }
  if (-not `$updated) { `$lines += "`$Key=`$Value" }
  Set-Content -Path `$Path -Value `$lines -Encoding UTF8
}
`$incomingOrigin = Get-OriginFromProtocolArg -Arg (`$args | Select-Object -First 1)
`$bootstrapToken = Get-QueryParamFromProtocolArg -Arg (`$args | Select-Object -First 1) -Name 'bootstrap_token'
if (-not [string]::IsNullOrWhiteSpace(`$incomingOrigin) -and (Test-Path `$envFile)) {
  `$existingOrigin = ''
  `$existingVerify = ''
  Get-Content `$envFile | ForEach-Object {
    `$line = (`$_.Trim())
    if ([string]::IsNullOrWhiteSpace(`$line) -or `$line.StartsWith('#')) { return }
    if (`$line -like 'ACCESSD_CONNECTOR_ALLOWED_ORIGIN=*') { `$existingOrigin = `$line.Split('=', 2)[1].Trim() }
    if (`$line -like 'ACCESSD_CONNECTOR_BACKEND_VERIFY_URL=*') { `$existingVerify = `$line.Split('=', 2)[1].Trim() }
  }
  if ([string]::IsNullOrWhiteSpace(`$existingOrigin) -or `$existingOrigin -like '*accessd.example.internal*') {
    Set-EnvValueInFile -Path `$envFile -Key 'ACCESSD_CONNECTOR_ALLOWED_ORIGIN' -Value `$incomingOrigin
  }
  if ([string]::IsNullOrWhiteSpace(`$existingVerify) -or `$existingVerify -like '*accessd.example.internal*') {
    Set-EnvValueInFile -Path `$envFile -Key 'ACCESSD_CONNECTOR_BACKEND_VERIFY_URL' -Value ("{0}/api/connector/token/verify" -f `$incomingOrigin)
  }
}
if (-not [string]::IsNullOrWhiteSpace(`$incomingOrigin) -and -not [string]::IsNullOrWhiteSpace(`$bootstrapToken) -and (Test-Path `$envFile)) {
  `$verifyEndpoint = ("{0}/api/connector/bootstrap/verify" -f `$incomingOrigin.TrimEnd('/'))
  try {
    `$body = @{ token = `$bootstrapToken } | ConvertTo-Json -Compress
    `$resp = Invoke-RestMethod -Method Post -Uri `$verifyEndpoint -ContentType 'application/json' -Body `$body -ErrorAction Stop
    if (`$resp.valid -eq `$true -and `$resp.claims) {
      if (`$resp.claims.origin) {
        Set-EnvValueInFile -Path `$envFile -Key 'ACCESSD_CONNECTOR_ALLOWED_ORIGIN' -Value ([string]`$resp.claims.origin)
      }
      if (`$resp.claims.backend_verify_url) {
        Set-EnvValueInFile -Path `$envFile -Key 'ACCESSD_CONNECTOR_BACKEND_VERIFY_URL' -Value ([string]`$resp.claims.backend_verify_url)
      }
    }
  } catch {
  }
}
if (Test-Path `$envFile) {
  Get-Content `$envFile | ForEach-Object {
    `$line = (`$_.Trim())
    if ([string]::IsNullOrWhiteSpace(`$line) -or `$line.StartsWith('#')) { return }
    if (`$line -notmatch '^[A-Za-z_][A-Za-z0-9_]*=') { return }
    `$parts = `$line.Split('=', 2)
    if (`$parts.Count -ne 2) { return }
    `$key = `$parts[0].Trim()
    `$value = Expand-EnvValue -Value `$parts[1]
    [System.Environment]::SetEnvironmentVariable(`$key, `$value, 'Process')
  }
}
`$connectorAddr = if ([string]::IsNullOrWhiteSpace(`$env:ACCESSD_CONNECTOR_ADDR)) { '127.0.0.1:9494' } else { `$env:ACCESSD_CONNECTOR_ADDR }
`$trustScript = Join-Path `$env:USERPROFILE '.accessd-connector\bin\trust-refresh-windows.ps1'
if ([string]::IsNullOrWhiteSpace(`$env:ACCESSD_CONNECTOR_SECRET) -and [string]::IsNullOrWhiteSpace(`$env:ACCESSD_CONNECTOR_BACKEND_VERIFY_URL)) {
  Write-Host '[accessd-connector] WARNING: token verification not configured (set ACCESSD_CONNECTOR_BACKEND_VERIFY_URL or ACCESSD_CONNECTOR_SECRET).'
}
try {
  [System.Net.ServicePointManager]::ServerCertificateValidationCallback = { `$true }
  try { Invoke-WebRequest -UseBasicParsing -Uri ("https://{0}/version" -f `$connectorAddr) -TimeoutSec 1 | Out-Null; exit 0 } catch {}
  Invoke-WebRequest -UseBasicParsing -Uri ("http://{0}/version" -f `$connectorAddr) -TimeoutSec 1 | Out-Null
  exit 0
} catch {
}
Start-Process -FilePath '$targetBin' -WindowStyle Hidden
"@ | Set-Content -Path $handlerScript -Encoding UTF8

$protocolRoot = 'HKCU:\Software\Classes\accessd-connector'
New-Item -Path $protocolRoot -Force | Out-Null
Set-ItemProperty -Path $protocolRoot -Name '(default)' -Value 'URL:AccessD Connector Protocol' -Force
Set-ItemProperty -Path $protocolRoot -Name 'URL Protocol' -Value '' -Force
New-Item -Path "$protocolRoot\\DefaultIcon" -Force | Out-Null
Set-ItemProperty -Path "$protocolRoot\\DefaultIcon" -Name '(default)' -Value "`"$targetBin`",0" -Force
New-Item -Path "$protocolRoot\\shell\\open\\command" -Force | Out-Null
$command = "powershell.exe -NoProfile -ExecutionPolicy Bypass -File `"$handlerScript`" `"%1`""
Set-ItemProperty -Path "$protocolRoot\\shell\\open\\command" -Name '(default)' -Value $command -Force

$dbeaverDetected = Resolve-CandidatePath @(
  'dbeaver.exe',
  'dbeaver',
  'C:\Program Files\DBeaver\dbeaver.exe',
  'C:\Program Files\DBeaver\DBeaver CE\dbeaver.exe',
  'C:\Program Files (x86)\DBeaver\dbeaver.exe'
)
$filezillaDetected = Resolve-CandidatePath @(
  'filezilla.exe',
  'filezilla',
  'C:\Program Files\FileZilla FTP Client\filezilla.exe',
  'C:\Program Files (x86)\FileZilla FTP Client\filezilla.exe'
)
$redisDetected = Resolve-CandidatePath @(
  'redis-cli.exe',
  'redis-cli',
  'C:\Program Files\Redis\redis-cli.exe',
  'C:\Program Files\Redis\bin\redis-cli.exe'
)
$puttyDetected = Resolve-CandidatePath @(
  'putty.exe',
  'putty',
  'C:\Program Files\PuTTY\putty.exe',
  'C:\Program Files (x86)\PuTTY\putty.exe'
)
$winscpDetected = Resolve-CandidatePath @(
  'winscp.exe',
  'winscp',
  'C:\Program Files\WinSCP\WinSCP.exe',
  'C:\Program Files (x86)\WinSCP\WinSCP.exe'
)

$terminalPref = Choose-TerminalPref
$dbeaverPath = Prompt-PathIfMissing -Label 'DBeaver' -Current $dbeaverDetected
$filezillaPath = Prompt-PathIfMissing -Label 'FileZilla' -Current $filezillaDetected
$redisCLIPath = Prompt-PathIfMissing -Label 'redis-cli' -Current $redisDetected
$puttyPath = Prompt-PathIfMissing -Label 'PuTTY (required for shell launch on Windows)' -Current $puttyDetected
$winscpPath = Prompt-PathIfMissing -Label 'WinSCP (recommended SFTP client on Windows)' -Current $winscpDetected

if (-not $puttyPath) {
  Write-Host '[accessd-connector] WARNING: PuTTY not configured. Shell launch on Windows will fail until PuTTY is installed/configured.'
}

Write-InstallerConfig -ConfigFile $configFile -DBeaverPath $dbeaverPath -FileZillaPath $filezillaPath -RedisCLIPath $redisCLIPath -PuTTYPath $puttyPath -WinSCPPath $winscpPath -TerminalPref $terminalPref
Bootstrap-RuntimeEnvFile -EnvFile $runtimeEnvFile
Write-RuntimeEnvFile -EnvFile $runtimeEnvFile
Load-EnvFileIntoProcess -Path $runtimeEnvFile
Trust-AccessDServerCert -RuntimeEnvFile $runtimeEnvFile
Trust-LocalConnectorTLSCert -ConnectorBinary $targetBin

if ($wasRunning) {
  Write-Host '[accessd-connector] Restarting connector after reinstall...'
}
$startReason = 'initial install'
if ($wasRunning) {
  $startReason = 'restart after reinstall'
}
if (-not (Start-ConnectorProcess -BinaryPath $targetBin -RuntimeEnvFile $runtimeEnvFile -Reason $startReason)) {
  Write-Host '[accessd-connector] WARNING: connector is not running yet; UI will still be able to start it via accessd-connector://start.'
}

Write-Host "[accessd-connector] Installed binary: $targetBin"
Write-Host "[accessd-connector] Runtime env file: $runtimeEnvFile"
Write-Host "[accessd-connector] Handler script: $handlerScript"
Write-Host "[accessd-connector] Registered URL scheme: accessd-connector://"
Write-Host "[accessd-connector] UI auto-start can now invoke accessd-connector://start"
