$ErrorActionPreference = 'Stop'

function Test-Interactive {
  try {
    return [Environment]::UserInteractive
  } catch {
    return $false
  }
}

function Resolve-CandidatePath {
  param([string[]]$Candidates)
  foreach ($c in $Candidates) {
    if ([string]::IsNullOrWhiteSpace($c)) { continue }
    if (Test-Path $c) { return $c }
    try {
      $cmd = Get-Command $c -ErrorAction Stop
      if ($cmd -and $cmd.Source) { return $cmd.Source }
    } catch {
    }
  }
  return $null
}

function Prompt-PathIfMissing {
  param(
    [string]$Label,
    [string]$Current
  )
  if (-not [string]::IsNullOrWhiteSpace($Current)) { return $Current }
  if (-not (Test-Interactive)) { return $null }
  while ($true) {
    $inputPath = Read-Host "[accessd-connector] $Label not detected. Enter full path or press Enter to skip"
    if ([string]::IsNullOrWhiteSpace($inputPath)) { return $null }
    if (Test-Path $inputPath) { return $inputPath }
    Write-Host "[accessd-connector] Path does not exist: $inputPath"
  }
}

function Choose-TerminalPref {
  $default = 'cmd'
  $wt = Resolve-CandidatePath @('wt.exe', 'wt')
  if ($wt) { $default = 'wt' }
  if (-not (Test-Interactive)) { return $default }
  Write-Host '[accessd-connector] Shell terminal preference'
  Write-Host '  1) cmd'
  Write-Host '  2) powershell'
  Write-Host '  3) wt'
  $choice = Read-Host "Select terminal [1-3, default $default]"
  switch ($choice) {
    '2' { return 'powershell' }
    'powershell' { return 'powershell' }
    '3' { return 'wt' }
    'wt' { return 'wt' }
    default { return $default }
  }
}

function Write-InstallerConfig {
  param(
    [string]$ConfigFile,
    [string]$DBeaverPath,
    [string]$FileZillaPath,
    [string]$RedisCLIPath,
    [string]$PuTTYPath,
    [string]$WinSCPPath,
    [string]$TerminalPref
  )

  $shouldWrite = $true
  if (Test-Path $ConfigFile) {
    $shouldWrite = $false
    if (Test-Interactive) {
      $replaceChoice = Read-Host "[accessd-connector] Existing config found at $ConfigFile. Replace with installer-detected paths? [y/N]"
      if ($replaceChoice -match '^(?i:y|yes)$') {
        $shouldWrite = $true
      }
    }
  }

  if (-not $shouldWrite) {
    Write-Host "[accessd-connector] Keeping existing config: $ConfigFile"
    return
  }

  $configDir = Split-Path -Parent $ConfigFile
  New-Item -ItemType Directory -Force -Path $configDir | Out-Null

  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add('# AccessD Connector config')
  $lines.Add('# Generated by installer')
  $lines.Add('apps:')
  if ($DBeaverPath) { $lines.Add("  dbeaver: `"$DBeaverPath`"") }
  if ($FileZillaPath) { $lines.Add("  filezilla: `"$FileZillaPath`"") }
  if ($RedisCLIPath) { $lines.Add("  redis_cli: `"$RedisCLIPath`"") }
  if ($PuTTYPath) { $lines.Add("  putty: `"$PuTTYPath`"") }
  if ($WinSCPPath) { $lines.Add("  winscp: `"$WinSCPPath`"") }
  $lines.Add('')
  $lines.Add('terminal:')
  $lines.Add("  windows: `"$TerminalPref`"")

  Set-Content -Path $ConfigFile -Value $lines -Encoding UTF8
  Write-Host "[accessd-connector] Wrote config: $ConfigFile"
}

function Write-RuntimeEnvFile {
  param([string]$EnvFile)

  $envDir = Split-Path -Parent $EnvFile
  New-Item -ItemType Directory -Force -Path $envDir | Out-Null
  if (Test-Path $EnvFile) {
    Write-Host "[accessd-connector] Keeping existing runtime env: $EnvFile"
    return
  }

  $defaultOrigin = if ([string]::IsNullOrWhiteSpace($env:ACCESSD_CONNECTOR_ALLOWED_ORIGIN)) {
    'https://accessd.example.internal'
  } else {
    $env:ACCESSD_CONNECTOR_ALLOWED_ORIGIN
  }

  $lines = @(
    '# AccessD Connector runtime env (non-sensitive defaults)'
    '# Keep secrets out of this file.'
    'ACCESSD_CONNECTOR_ADDR=127.0.0.1:9494'
    "ACCESSD_CONNECTOR_ALLOWED_ORIGIN=$defaultOrigin"
    'ACCESSD_CONNECTOR_ALLOW_ANY_ORIGIN=false'
    'ACCESSD_CONNECTOR_ALLOW_REMOTE=false'
    'ACCESSD_CONNECTOR_AUTO_TRUST_SERVER_CERT=true'
    '# ACCESSD_CONNECTOR_TRUST_CERT_URL=https://accessd.example.internal/downloads/certs/accessd-server.crt'
    ''
    '# Optional: set ACCESSD_CONNECTOR_SECRET in system environment'
    '# (recommended) instead of storing it here.'
  )
  Set-Content -Path $EnvFile -Value $lines -Encoding UTF8
  Write-Host "[accessd-connector] Wrote runtime env: $EnvFile"
}

function Get-OriginHost {
  param([string]$Origin)
  if ([string]::IsNullOrWhiteSpace($Origin)) { return $null }
  try {
    return ([Uri]$Origin).Host
  } catch {
    return $null
  }
}

function Save-RemoteServerCert {
  param(
    [string]$Host,
    [string]$OutFile
  )
  $tcp = $null
  $ssl = $null
  try {
    $tcp = New-Object System.Net.Sockets.TcpClient($Host, 443)
    $ssl = New-Object System.Net.Security.SslStream($tcp.GetStream(), $false, ({ $true }))
    $ssl.AuthenticateAsClient($Host)
    $remote = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2($ssl.RemoteCertificate)
    [System.IO.File]::WriteAllBytes($OutFile, $remote.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Cert))
    return $true
  } catch {
    return $false
  } finally {
    if ($ssl) { $ssl.Dispose() }
    if ($tcp) { $tcp.Close() }
  }
}

function Trust-AccessDServerCert {
  param([string]$RuntimeEnvFile)

  $autoTrust = $env:ACCESSD_CONNECTOR_AUTO_TRUST_SERVER_CERT
  if (-not [string]::IsNullOrWhiteSpace($autoTrust) -and $autoTrust -match '^(?i:false|0|no|off)$') {
    Write-Host "[accessd-connector] Auto trust disabled (ACCESSD_CONNECTOR_AUTO_TRUST_SERVER_CERT=$autoTrust)."
    return
  }

  $origin = $env:ACCESSD_CONNECTOR_ALLOWED_ORIGIN
  $host = Get-OriginHost -Origin $origin
  if ([string]::IsNullOrWhiteSpace($host) -or $host -in @('localhost', '127.0.0.1', 'accessd.example.internal')) {
    return
  }

  $certDir = Join-Path $configDir 'certs'
  New-Item -ItemType Directory -Force -Path $certDir | Out-Null
  $certFile = Join-Path $certDir ("accessd-{0}.cer" -f $host)

  $saved = Save-RemoteServerCert -Host $host -OutFile $certFile
  if (-not $saved) {
    Write-Host "[accessd-connector] WARNING: failed to fetch TLS certificate from $host:443"
    return
  }

  try {
    Import-Certificate -FilePath $certFile -CertStoreLocation 'Cert:\CurrentUser\Root' | Out-Null
    Write-Host "[accessd-connector] Installed server cert into CurrentUser Root trust store: $certFile"
  } catch {
    Write-Host "[accessd-connector] WARNING: failed to import cert into CurrentUser Root: $($_.Exception.Message)"
    Write-Host "[accessd-connector] Saved cert at: $certFile"
  }
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$sourceBin = Join-Path $scriptDir 'accessd-connector.exe'
if (-not (Test-Path $sourceBin)) {
  $sourceBin = Join-Path (Split-Path -Parent $scriptDir) 'accessd-connector.exe'
}
if (-not (Test-Path $sourceBin)) {
  throw "[accessd-connector] accessd-connector.exe not found next to installer"
}

$installDir = if ($env:ACCESSD_CONNECTOR_INSTALL_DIR) { $env:ACCESSD_CONNECTOR_INSTALL_DIR } else { Join-Path $env:LOCALAPPDATA 'AccessD\\bin' }
$configDir = Join-Path $env:USERPROFILE '.accessd-connector'
$configFile = Join-Path $configDir 'config.yaml'
$helperDir = Join-Path $configDir 'bin'
$runtimeEnvFile = Join-Path (Join-Path $env:USERPROFILE '.config\accessd') 'connector.env'
$targetBin = Join-Path $installDir 'accessd-connector.exe'
$handlerScript = Join-Path $helperDir 'url-handler-windows.ps1'
$trustHelperScript = Join-Path $helperDir 'trust-refresh-windows.ps1'

New-Item -ItemType Directory -Force -Path $installDir | Out-Null
New-Item -ItemType Directory -Force -Path $helperDir | Out-Null

$wasRunning = $false
try {
  $running = Get-Process -Name 'accessd-connector' -ErrorAction SilentlyContinue
  if ($running) {
    $wasRunning = $true
    Write-Host '[accessd-connector] Existing connector process detected. Stopping before reinstall...'
    $running | Stop-Process -Force -ErrorAction SilentlyContinue
    Start-Sleep -Milliseconds 600
  }
} catch {
}

Copy-Item -Force $sourceBin $targetBin

@"
`$ErrorActionPreference = 'SilentlyContinue'
function Get-OriginHost {
  param([string]`$Origin)
  if ([string]::IsNullOrWhiteSpace(`$Origin)) { return `$null }
  try { return ([Uri]`$Origin).Host } catch { return `$null }
}
function Save-RemoteServerCert {
  param([string]`$Host, [string]`$OutFile)
  `$tcp = `$null
  `$ssl = `$null
  try {
    `$tcp = New-Object System.Net.Sockets.TcpClient(`$Host, 443)
    `$ssl = New-Object System.Net.Security.SslStream(`$tcp.GetStream(), `$false, ({ `$true }))
    `$ssl.AuthenticateAsClient(`$Host)
    `$remote = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2(`$ssl.RemoteCertificate)
    [System.IO.File]::WriteAllBytes(`$OutFile, `$remote.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Cert))
    return `$true
  } catch {
    return `$false
  } finally {
    if (`$ssl) { `$ssl.Dispose() }
    if (`$tcp) { `$tcp.Close() }
  }
}
`$envFile = Join-Path `$env:USERPROFILE '.config\accessd\connector.env'
if (Test-Path `$envFile) {
  Get-Content `$envFile | ForEach-Object {
    `$line = (`$_.Trim())
    if ([string]::IsNullOrWhiteSpace(`$line) -or `$line.StartsWith('#')) { return }
    if (`$line -notmatch '^[A-Za-z_][A-Za-z0-9_]*=') { return }
    `$parts = `$line.Split('=', 2)
    if (`$parts.Count -ne 2) { return }
    `$key = `$parts[0].Trim()
    `$value = `$parts[1].Trim().Trim('"').Trim("'")
    [System.Environment]::SetEnvironmentVariable(`$key, `$value, 'Process')
  }
}
`$autoTrust = `$env:ACCESSD_CONNECTOR_AUTO_TRUST_SERVER_CERT
if (-not [string]::IsNullOrWhiteSpace(`$autoTrust) -and `$autoTrust -match '^(?i:false|0|no|off)$') { exit 0 }
`$host = Get-OriginHost -Origin `$env:ACCESSD_CONNECTOR_ALLOWED_ORIGIN
if ([string]::IsNullOrWhiteSpace(`$host) -or `$host -in @('localhost', '127.0.0.1', 'accessd.example.internal')) { exit 0 }
`$certDir = Join-Path `$env:USERPROFILE '.accessd-connector\certs'
New-Item -ItemType Directory -Force -Path `$certDir | Out-Null
`$certFile = Join-Path `$certDir ("accessd-{0}.cer" -f `$host)
if (-not (Save-RemoteServerCert -Host `$host -OutFile `$certFile)) { exit 0 }
Import-Certificate -FilePath `$certFile -CertStoreLocation 'Cert:\CurrentUser\Root' | Out-Null
"@ | Set-Content -Path $trustHelperScript -Encoding UTF8

@"
`$ErrorActionPreference = 'SilentlyContinue'
$envFile = Join-Path `$env:USERPROFILE '.config\accessd\connector.env'
if (Test-Path `$envFile) {
  Get-Content `$envFile | ForEach-Object {
    `$line = (`$_.Trim())
    if ([string]::IsNullOrWhiteSpace(`$line) -or `$line.StartsWith('#')) { return }
    if (`$line -notmatch '^[A-Za-z_][A-Za-z0-9_]*=') { return }
    `$parts = `$line.Split('=', 2)
    if (`$parts.Count -ne 2) { return }
    `$key = `$parts[0].Trim()
    `$value = `$parts[1].Trim().Trim('"').Trim("'")
    [System.Environment]::SetEnvironmentVariable(`$key, `$value, 'Process')
  }
}
`$connectorAddr = if ([string]::IsNullOrWhiteSpace(`$env:ACCESSD_CONNECTOR_ADDR)) { '127.0.0.1:9494' } else { `$env:ACCESSD_CONNECTOR_ADDR }
`$trustScript = Join-Path `$env:USERPROFILE '.accessd-connector\bin\trust-refresh-windows.ps1'
if ([string]::IsNullOrWhiteSpace(`$env:ACCESSD_CONNECTOR_SECRET)) {
  Write-Host '[accessd-connector] WARNING: ACCESSD_CONNECTOR_SECRET is not set in process env.'
}
if (Test-Path `$trustScript) { powershell.exe -NoProfile -ExecutionPolicy Bypass -File `$trustScript | Out-Null }
try {
  Invoke-WebRequest -UseBasicParsing -Uri ("http://{0}/version" -f `$connectorAddr) -TimeoutSec 1 | Out-Null
  exit 0
} catch {
}
Start-Process -FilePath '$targetBin' -WindowStyle Hidden
"@ | Set-Content -Path $handlerScript -Encoding UTF8

$protocolRoot = 'HKCU:\Software\Classes\accessd-connector'
New-Item -Path $protocolRoot -Force | Out-Null
Set-ItemProperty -Path $protocolRoot -Name '(default)' -Value 'URL:AccessD Connector Protocol' -Force
Set-ItemProperty -Path $protocolRoot -Name 'URL Protocol' -Value '' -Force
New-Item -Path "$protocolRoot\\DefaultIcon" -Force | Out-Null
Set-ItemProperty -Path "$protocolRoot\\DefaultIcon" -Name '(default)' -Value "`"$targetBin`",0" -Force
New-Item -Path "$protocolRoot\\shell\\open\\command" -Force | Out-Null
$command = "powershell.exe -NoProfile -ExecutionPolicy Bypass -File `"$handlerScript`" `"%1`""
Set-ItemProperty -Path "$protocolRoot\\shell\\open\\command" -Name '(default)' -Value $command -Force

$dbeaverDetected = Resolve-CandidatePath @(
  'dbeaver.exe',
  'dbeaver',
  'C:\Program Files\DBeaver\dbeaver.exe',
  'C:\Program Files\DBeaver\DBeaver CE\dbeaver.exe',
  'C:\Program Files (x86)\DBeaver\dbeaver.exe'
)
$filezillaDetected = Resolve-CandidatePath @(
  'filezilla.exe',
  'filezilla',
  'C:\Program Files\FileZilla FTP Client\filezilla.exe',
  'C:\Program Files (x86)\FileZilla FTP Client\filezilla.exe'
)
$redisDetected = Resolve-CandidatePath @(
  'redis-cli.exe',
  'redis-cli',
  'C:\Program Files\Redis\redis-cli.exe',
  'C:\Program Files\Redis\bin\redis-cli.exe'
)
$puttyDetected = Resolve-CandidatePath @(
  'putty.exe',
  'putty',
  'C:\Program Files\PuTTY\putty.exe',
  'C:\Program Files (x86)\PuTTY\putty.exe'
)
$winscpDetected = Resolve-CandidatePath @(
  'winscp.exe',
  'winscp',
  'C:\Program Files\WinSCP\WinSCP.exe',
  'C:\Program Files (x86)\WinSCP\WinSCP.exe'
)

$terminalPref = Choose-TerminalPref
$dbeaverPath = Prompt-PathIfMissing -Label 'DBeaver' -Current $dbeaverDetected
$filezillaPath = Prompt-PathIfMissing -Label 'FileZilla' -Current $filezillaDetected
$redisCLIPath = Prompt-PathIfMissing -Label 'redis-cli' -Current $redisDetected
$puttyPath = Prompt-PathIfMissing -Label 'PuTTY (required for shell launch on Windows)' -Current $puttyDetected
$winscpPath = Prompt-PathIfMissing -Label 'WinSCP (recommended SFTP client on Windows)' -Current $winscpDetected

if (-not $puttyPath) {
  Write-Host '[accessd-connector] WARNING: PuTTY not configured. Shell launch on Windows will fail until PuTTY is installed/configured.'
}

Write-InstallerConfig -ConfigFile $configFile -DBeaverPath $dbeaverPath -FileZillaPath $filezillaPath -RedisCLIPath $redisCLIPath -PuTTYPath $puttyPath -WinSCPPath $winscpPath -TerminalPref $terminalPref
Write-RuntimeEnvFile -EnvFile $runtimeEnvFile
if (Test-Path $runtimeEnvFile) {
  Get-Content $runtimeEnvFile | ForEach-Object {
    $line = ($_.Trim())
    if ([string]::IsNullOrWhiteSpace($line) -or $line.StartsWith('#')) { return }
    if ($line -notmatch '^[A-Za-z_][A-Za-z0-9_]*=') { return }
    $parts = $line.Split('=', 2)
    if ($parts.Count -ne 2) { return }
    $key = $parts[0].Trim()
    $value = $parts[1].Trim().Trim('"').Trim("'")
    [System.Environment]::SetEnvironmentVariable($key, $value, 'Process')
  }
}
Trust-AccessDServerCert -RuntimeEnvFile $runtimeEnvFile

if ($wasRunning) {
  Write-Host '[accessd-connector] Restarting connector after reinstall...'
  try {
    if (Test-Path $runtimeEnvFile) {
      Get-Content $runtimeEnvFile | ForEach-Object {
        $line = ($_.Trim())
        if ([string]::IsNullOrWhiteSpace($line) -or $line.StartsWith('#')) { return }
        if ($line -notmatch '^[A-Za-z_][A-Za-z0-9_]*=') { return }
        $parts = $line.Split('=', 2)
        if ($parts.Count -ne 2) { return }
        $key = $parts[0].Trim()
        $value = $parts[1].Trim().Trim('"').Trim("'")
        [System.Environment]::SetEnvironmentVariable($key, $value, 'Process')
      }
    }
    Start-Process -FilePath $targetBin -WindowStyle Hidden | Out-Null
  } catch {
    Write-Host "[accessd-connector] WARNING: failed to restart connector automatically: $($_.Exception.Message)"
  }
}

Write-Host "[accessd-connector] Installed binary: $targetBin"
Write-Host "[accessd-connector] Runtime env file: $runtimeEnvFile"
Write-Host "[accessd-connector] Handler script: $handlerScript"
Write-Host "[accessd-connector] Registered URL scheme: accessd-connector://"
Write-Host "[accessd-connector] UI auto-start can now invoke accessd-connector://start"
