$ErrorActionPreference = 'Stop'

function Test-Interactive {
  try {
    return [Environment]::UserInteractive
  } catch {
    return $false
  }
}

function Resolve-CandidatePath {
  param([string[]]$Candidates)
  foreach ($c in $Candidates) {
    if ([string]::IsNullOrWhiteSpace($c)) { continue }
    if (Test-Path $c) { return $c }
    try {
      $cmd = Get-Command $c -ErrorAction Stop
      if ($cmd -and $cmd.Source) { return $cmd.Source }
    } catch {
    }
  }
  return $null
}

function Prompt-PathIfMissing {
  param(
    [string]$Label,
    [string]$Current
  )
  if (-not [string]::IsNullOrWhiteSpace($Current)) { return $Current }
  if (-not (Test-Interactive)) { return $null }
  while ($true) {
    $inputPath = Read-Host "[accessd-connector] $Label not detected. Enter full path or press Enter to skip"
    if ([string]::IsNullOrWhiteSpace($inputPath)) { return $null }
    if (Test-Path $inputPath) { return $inputPath }
    Write-Host "[accessd-connector] Path does not exist: $inputPath"
  }
}

function Choose-TerminalPref {
  $default = 'cmd'
  $wt = Resolve-CandidatePath @('wt.exe', 'wt')
  if ($wt) { $default = 'wt' }
  if (-not (Test-Interactive)) { return $default }
  Write-Host '[accessd-connector] Shell terminal preference'
  Write-Host '  1) cmd'
  Write-Host '  2) powershell'
  Write-Host '  3) wt'
  $choice = Read-Host "Select terminal [1-3, default $default]"
  switch ($choice) {
    '2' { return 'powershell' }
    'powershell' { return 'powershell' }
    '3' { return 'wt' }
    'wt' { return 'wt' }
    default { return $default }
  }
}

function Write-InstallerConfig {
  param(
    [string]$ConfigFile,
    [string]$DBeaverPath,
    [string]$FileZillaPath,
    [string]$RedisCLIPath,
    [string]$PuTTYPath,
    [string]$WinSCPPath,
    [string]$TerminalPref
  )

  $shouldWrite = $true
  if (Test-Path $ConfigFile) {
    $shouldWrite = $false
    if (Test-Interactive) {
      $replaceChoice = Read-Host "[accessd-connector] Existing config found at $ConfigFile. Replace with installer-detected paths? [y/N]"
      if ($replaceChoice -match '^(?i:y|yes)$') {
        $shouldWrite = $true
      }
    }
  }

  if (-not $shouldWrite) {
    Write-Host "[accessd-connector] Keeping existing config: $ConfigFile"
    return
  }

  $configDir = Split-Path -Parent $ConfigFile
  New-Item -ItemType Directory -Force -Path $configDir | Out-Null

  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add('# AccessD Connector config')
  $lines.Add('# Generated by installer')
  $lines.Add('apps:')
  if ($DBeaverPath) { $lines.Add("  dbeaver: `"$DBeaverPath`"") }
  if ($FileZillaPath) { $lines.Add("  filezilla: `"$FileZillaPath`"") }
  if ($RedisCLIPath) { $lines.Add("  redis_cli: `"$RedisCLIPath`"") }
  if ($PuTTYPath) { $lines.Add("  putty: `"$PuTTYPath`"") }
  if ($WinSCPPath) { $lines.Add("  winscp: `"$WinSCPPath`"") }
  $lines.Add('')
  $lines.Add('terminal:')
  $lines.Add("  windows: `"$TerminalPref`"")

  Set-Content -Path $ConfigFile -Value $lines -Encoding UTF8
  Write-Host "[accessd-connector] Wrote config: $ConfigFile"
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$sourceBin = Join-Path $scriptDir 'accessd-connector.exe'
if (-not (Test-Path $sourceBin)) {
  $sourceBin = Join-Path (Split-Path -Parent $scriptDir) 'accessd-connector.exe'
}
if (-not (Test-Path $sourceBin)) {
  throw "[accessd-connector] accessd-connector.exe not found next to installer"
}

$installDir = if ($env:ACCESSD_CONNECTOR_INSTALL_DIR) { $env:ACCESSD_CONNECTOR_INSTALL_DIR } else { Join-Path $env:LOCALAPPDATA 'AccessD\\bin' }
$configDir = Join-Path $env:USERPROFILE '.accessd-connector'
$configFile = Join-Path $configDir 'config.yaml'
$helperDir = Join-Path $configDir 'bin'
$targetBin = Join-Path $installDir 'accessd-connector.exe'
$handlerScript = Join-Path $helperDir 'url-handler-windows.ps1'

New-Item -ItemType Directory -Force -Path $installDir | Out-Null
New-Item -ItemType Directory -Force -Path $helperDir | Out-Null

$wasRunning = $false
try {
  $running = Get-Process -Name 'accessd-connector' -ErrorAction SilentlyContinue
  if ($running) {
    $wasRunning = $true
    Write-Host '[accessd-connector] Existing connector process detected. Stopping before reinstall...'
    $running | Stop-Process -Force -ErrorAction SilentlyContinue
    Start-Sleep -Milliseconds 600
  }
} catch {
}

Copy-Item -Force $sourceBin $targetBin

@"
`$ErrorActionPreference = 'SilentlyContinue'
try {
  Invoke-WebRequest -UseBasicParsing -Uri 'http://127.0.0.1:9494/version' -TimeoutSec 1 | Out-Null
  exit 0
} catch {
}
Start-Process -FilePath '$targetBin' -WindowStyle Hidden
"@ | Set-Content -Path $handlerScript -Encoding UTF8

$protocolRoot = 'HKCU:\Software\Classes\accessd-connector'
New-Item -Path $protocolRoot -Force | Out-Null
Set-ItemProperty -Path $protocolRoot -Name '(default)' -Value 'URL:AccessD Connector Protocol' -Force
Set-ItemProperty -Path $protocolRoot -Name 'URL Protocol' -Value '' -Force
New-Item -Path "$protocolRoot\\DefaultIcon" -Force | Out-Null
Set-ItemProperty -Path "$protocolRoot\\DefaultIcon" -Name '(default)' -Value "`"$targetBin`",0" -Force
New-Item -Path "$protocolRoot\\shell\\open\\command" -Force | Out-Null
$command = "powershell.exe -NoProfile -ExecutionPolicy Bypass -File `"$handlerScript`" `"%1`""
Set-ItemProperty -Path "$protocolRoot\\shell\\open\\command" -Name '(default)' -Value $command -Force

$dbeaverDetected = Resolve-CandidatePath @(
  'dbeaver.exe',
  'dbeaver',
  'C:\Program Files\DBeaver\dbeaver.exe',
  'C:\Program Files\DBeaver\DBeaver CE\dbeaver.exe',
  'C:\Program Files (x86)\DBeaver\dbeaver.exe'
)
$filezillaDetected = Resolve-CandidatePath @(
  'filezilla.exe',
  'filezilla',
  'C:\Program Files\FileZilla FTP Client\filezilla.exe',
  'C:\Program Files (x86)\FileZilla FTP Client\filezilla.exe'
)
$redisDetected = Resolve-CandidatePath @(
  'redis-cli.exe',
  'redis-cli',
  'C:\Program Files\Redis\redis-cli.exe',
  'C:\Program Files\Redis\bin\redis-cli.exe'
)
$puttyDetected = Resolve-CandidatePath @(
  'putty.exe',
  'putty',
  'C:\Program Files\PuTTY\putty.exe',
  'C:\Program Files (x86)\PuTTY\putty.exe'
)
$winscpDetected = Resolve-CandidatePath @(
  'winscp.exe',
  'winscp',
  'C:\Program Files\WinSCP\WinSCP.exe',
  'C:\Program Files (x86)\WinSCP\WinSCP.exe'
)

$terminalPref = Choose-TerminalPref
$dbeaverPath = Prompt-PathIfMissing -Label 'DBeaver' -Current $dbeaverDetected
$filezillaPath = Prompt-PathIfMissing -Label 'FileZilla' -Current $filezillaDetected
$redisCLIPath = Prompt-PathIfMissing -Label 'redis-cli' -Current $redisDetected
$puttyPath = Prompt-PathIfMissing -Label 'PuTTY (required for shell launch on Windows)' -Current $puttyDetected
$winscpPath = Prompt-PathIfMissing -Label 'WinSCP (recommended SFTP client on Windows)' -Current $winscpDetected

if (-not $puttyPath) {
  Write-Host '[accessd-connector] WARNING: PuTTY not configured. Shell launch on Windows will fail until PuTTY is installed/configured.'
}

Write-InstallerConfig -ConfigFile $configFile -DBeaverPath $dbeaverPath -FileZillaPath $filezillaPath -RedisCLIPath $redisCLIPath -PuTTYPath $puttyPath -WinSCPPath $winscpPath -TerminalPref $terminalPref

if ($wasRunning) {
  Write-Host '[accessd-connector] Restarting connector after reinstall...'
  try {
    Start-Process -FilePath $targetBin -WindowStyle Hidden | Out-Null
  } catch {
    Write-Host "[accessd-connector] WARNING: failed to restart connector automatically: $($_.Exception.Message)"
  }
}

Write-Host "[accessd-connector] Installed binary: $targetBin"
Write-Host "[accessd-connector] Handler script: $handlerScript"
Write-Host "[accessd-connector] Registered URL scheme: accessd-connector://"
Write-Host "[accessd-connector] UI auto-start can now invoke accessd-connector://start"
