#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_BIN="${SCRIPT_DIR}/accessd-connector"
if [[ ! -f "${SOURCE_BIN}" ]]; then
  SOURCE_BIN="${SCRIPT_DIR}/../accessd-connector"
fi
if [[ ! -f "${SOURCE_BIN}" ]]; then
  echo "[accessd-connector] binary not found next to installer"
  echo "Place this script beside accessd-connector and re-run."
  exit 1
fi

INSTALL_DIR="${ACCESSD_CONNECTOR_INSTALL_DIR:-${HOME}/.local/bin}"
CONFIG_DIR="${HOME}/.accessd-connector"
CONFIG_FILE="${CONFIG_DIR}/config.yaml"
ENV_DIR="${HOME}/.config/accessd"
ENV_FILE="${ENV_DIR}/connector.env"
HELPER_DIR="${CONFIG_DIR}/bin"
DESKTOP_DIR="${HOME}/.local/share/applications"
TARGET_BIN="${INSTALL_DIR}/accessd-connector"
HANDLER_SCRIPT="${HELPER_DIR}/url-handler-linux.sh"
TRUST_SCRIPT="${HELPER_DIR}/trust-refresh-linux.sh"
DESKTOP_FILE="${DESKTOP_DIR}/accessd-connector.desktop"

has_tty() {
  [[ -t 0 && -t 1 ]]
}

trim() {
  local s="$1"
  s="${s#${s%%[![:space:]]*}}"
  s="${s%${s##*[![:space:]]}}"
  printf '%s' "$s"
}

origin_host() {
  local origin="$1"
  origin="$(trim "${origin}")"
  origin="${origin#http://}"
  origin="${origin#https://}"
  origin="${origin%%/*}"
  origin="${origin%%:*}"
  printf '%s' "${origin}"
}

pick_existing_path() {
  for candidate in "$@"; do
    [[ -z "${candidate}" ]] && continue
    if [[ -e "${candidate}" ]]; then
      printf '%s' "${candidate}"
      return 0
    fi
  done
  return 1
}

prompt_for_path_if_missing() {
  local label="$1"
  local current="$2"
  if [[ -n "${current}" ]]; then
    printf '%s' "${current}"
    return 0
  fi
  if ! has_tty; then
    printf ''
    return 0
  fi
  while true; do
    read -r -p "[accessd-connector] ${label} not detected. Enter full path or press Enter to skip: " input
    input="$(trim "${input}")"
    if [[ -z "${input}" ]]; then
      printf ''
      return 0
    fi
    if [[ -e "${input}" ]]; then
      printf '%s' "${input}"
      return 0
    fi
    echo "[accessd-connector] Path does not exist: ${input}"
  done
}

choose_terminal_pref() {
  local default="auto"
  if command -v gnome-terminal >/dev/null 2>&1; then
    default="gnome-terminal"
  elif command -v konsole >/dev/null 2>&1; then
    default="konsole"
  elif command -v xfce4-terminal >/dev/null 2>&1; then
    default="xfce4-terminal"
  elif command -v xterm >/dev/null 2>&1; then
    default="xterm"
  fi
  if ! has_tty; then
    printf '%s' "${default}"
    return 0
  fi
  echo "[accessd-connector] Shell terminal preference"
  echo "  1) auto"
  echo "  2) gnome-terminal"
  echo "  3) konsole"
  echo "  4) xfce4-terminal"
  echo "  5) xterm"
  read -r -p "Select terminal [1-5, default ${default}]: " choice
  choice="$(trim "${choice}")"
  case "${choice}" in
    2|gnome-terminal) printf 'gnome-terminal' ;;
    3|konsole) printf 'konsole' ;;
    4|xfce4-terminal) printf 'xfce4-terminal' ;;
    5|xterm) printf 'xterm' ;;
    1|auto|"") printf '%s' "${default}" ;;
    *) printf '%s' "${default}" ;;
  esac
}

write_installer_config() {
  local dbeaver_path="$1"
  local filezilla_path="$2"
  local redis_cli_path="$3"
  local terminal_pref="$4"

  local should_write="1"
  if [[ -f "${CONFIG_FILE}" ]]; then
    should_write="0"
    if has_tty; then
      read -r -p "[accessd-connector] Existing config found at ${CONFIG_FILE}. Replace with installer-detected paths? [y/N]: " replace_choice
      replace_choice="$(trim "${replace_choice}")"
      case "${replace_choice}" in
        y|Y|yes|YES)
          should_write="1"
          ;;
      esac
    fi
  fi

  if [[ "${should_write}" != "1" ]]; then
    echo "[accessd-connector] Keeping existing config: ${CONFIG_FILE}"
    return 0
  fi

  mkdir -p "${CONFIG_DIR}"
  {
    echo "# AccessD Connector config"
    echo "# Generated by installer"
    echo "apps:"
    if [[ -n "${dbeaver_path}" ]]; then
      echo "  dbeaver: \"${dbeaver_path}\""
    fi
    if [[ -n "${filezilla_path}" ]]; then
      echo "  filezilla: \"${filezilla_path}\""
    fi
    if [[ -n "${redis_cli_path}" ]]; then
      echo "  redis_cli: \"${redis_cli_path}\""
    fi
    echo ""
    echo "terminal:"
    echo "  linux: \"${terminal_pref}\""
  } > "${CONFIG_FILE}"
  chmod 0600 "${CONFIG_FILE}"
  echo "[accessd-connector] Wrote config: ${CONFIG_FILE}"
}

write_runtime_env_file() {
  local default_origin="${ACCESSD_CONNECTOR_ALLOWED_ORIGIN:-https://accessd.example.internal}"
  mkdir -p "${ENV_DIR}"
  if [[ -f "${ENV_FILE}" ]]; then
    echo "[accessd-connector] Keeping existing runtime env: ${ENV_FILE}"
    return 0
  fi

  {
    echo "# AccessD Connector runtime env (non-sensitive defaults)"
    echo "# Keep secrets out of this file."
    echo "ACCESSD_CONNECTOR_ADDR=127.0.0.1:9494"
    echo "ACCESSD_CONNECTOR_ALLOWED_ORIGIN=${default_origin}"
    echo "# Optional backend online token verification endpoint."
    echo "# If unset, connector derives: <allowed_origin>/api/connector/token/verify"
    echo "# ACCESSD_CONNECTOR_BACKEND_VERIFY_URL=https://accessd.example.internal/api/connector/token/verify"
    echo "ACCESSD_CONNECTOR_ALLOW_ANY_ORIGIN=false"
    echo "ACCESSD_CONNECTOR_ALLOW_REMOTE=false"
    echo "# Optional bootstrap env URL. Default if unset:"
    echo "# https://<ACCESSD_CONNECTOR_ALLOWED_ORIGIN host>/downloads/bootstrap/accessd-connector.env"
    echo "# ACCESSD_CONNECTOR_BOOTSTRAP_ENV_URL=https://accessd.example.internal/downloads/bootstrap/accessd-connector.env"
    echo "ACCESSD_CONNECTOR_AUTO_TRUST_SERVER_CERT=true"
    echo "# ACCESSD_CONNECTOR_TRUST_CERT_URL=https://accessd.example.internal/downloads/certs/accessd-server.crt"
    echo ""
    echo "# Optional legacy local-HMAC mode:"
    echo "# ACCESSD_CONNECTOR_SECRET=<shared-secret>"
  } > "${ENV_FILE}"
  chmod 0600 "${ENV_FILE}"
  echo "[accessd-connector] Wrote runtime env: ${ENV_FILE}"
}

bootstrap_runtime_env_from_server() {
  mkdir -p "${ENV_DIR}"
  if [[ -f "${ENV_FILE}" ]]; then
    return 0
  fi

  local origin="${ACCESSD_CONNECTOR_ALLOWED_ORIGIN:-https://accessd.example.internal}"
  local host
  host="$(origin_host "${origin}")"
  if [[ -z "${host}" || "${host}" == "accessd.example.internal" ]]; then
    return 0
  fi
  local env_url="${ACCESSD_CONNECTOR_BOOTSTRAP_ENV_URL:-https://${host}/downloads/bootstrap/accessd-connector.env}"
  local tmp_env="${ENV_FILE}.tmp.$$"

  if ! command -v curl >/dev/null 2>&1; then
    return 0
  fi
  if ! curl -fsS -k -L "${env_url}" -o "${tmp_env}"; then
    rm -f "${tmp_env}" || true
    return 0
  fi
  if ! grep -q '^ACCESSD_CONNECTOR_ADDR=' "${tmp_env}"; then
    rm -f "${tmp_env}" || true
    return 0
  fi
  mv "${tmp_env}" "${ENV_FILE}"
  chmod 0600 "${ENV_FILE}"
  echo "[accessd-connector] Downloaded runtime env from ${env_url}"
}

write_trust_refresh_script() {
  cat > "${TRUST_SCRIPT}" <<'TRUST'
#!/usr/bin/env bash
set -euo pipefail

trim() {
  local s="$1"
  s="${s#${s%%[![:space:]]*}}"
  s="${s%${s##*[![:space:]]}}"
  printf '%s' "$s"
}

origin_host() {
  local origin="$1"
  origin="$(trim "${origin}")"
  origin="${origin#http://}"
  origin="${origin#https://}"
  origin="${origin%%/*}"
  origin="${origin%%:*}"
  printf '%s' "${origin}"
}

ENV_FILE="${HOME}/.config/accessd/connector.env"
if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # shellcheck disable=SC1090
  . "${ENV_FILE}"
  set +a
fi

auto_trust="${ACCESSD_CONNECTOR_AUTO_TRUST_SERVER_CERT:-true}"
case "${auto_trust,,}" in
  0|false|no|off)
    exit 0
    ;;
esac

host="$(origin_host "${ACCESSD_CONNECTOR_ALLOWED_ORIGIN:-}")"
if [[ -z "${host}" || "${host}" == "localhost" || "${host}" == "127.0.0.1" || "${host}" == "accessd.example.internal" ]]; then
  exit 0
fi

cert_url="${ACCESSD_CONNECTOR_TRUST_CERT_URL:-https://${host}/downloads/certs/accessd-server.crt}"
cert_dir="${HOME}/.accessd-connector/certs"
cert_file="${cert_dir}/accessd-${host}.crt"
mkdir -p "${cert_dir}"

if ! command -v curl >/dev/null 2>&1; then
  exit 0
fi
if ! curl -fsS -k -L "${cert_url}" -o "${cert_file}"; then
  exit 0
fi

if command -v update-ca-certificates >/dev/null 2>&1; then
  target="/usr/local/share/ca-certificates/accessd-${host}.crt"
  if [[ "$(id -u)" -eq 0 ]]; then
    cp "${cert_file}" "${target}" && update-ca-certificates >/dev/null 2>&1 || true
    exit 0
  fi
  if command -v sudo >/dev/null 2>&1 && sudo -n true >/dev/null 2>&1; then
    sudo cp "${cert_file}" "${target}" && sudo update-ca-certificates >/dev/null 2>&1 || true
    exit 0
  fi
fi
TRUST
  chmod 0755 "${TRUST_SCRIPT}"
}

trust_accessd_server_cert() {
  if [[ -x "${TRUST_SCRIPT}" ]]; then
    "${TRUST_SCRIPT}" || true
  fi
}

is_connector_running() {
  if curl -fsS --max-time 1 "http://127.0.0.1:9494/version" >/dev/null 2>&1; then
    return 0
  fi
  if pgrep -x "accessd-connector" >/dev/null 2>&1; then
    return 0
  fi
  return 1
}

stop_running_connector() {
  if ! pgrep -x "accessd-connector" >/dev/null 2>&1; then
    return 0
  fi
  pkill -x "accessd-connector" >/dev/null 2>&1 || true
  for _ in {1..20}; do
    if ! pgrep -x "accessd-connector" >/dev/null 2>&1; then
      return 0
    fi
    sleep 0.2
  done
  return 1
}

start_connector() {
  if [[ -f "${ENV_FILE}" ]]; then
    set -a
    # shellcheck disable=SC1090
    . "${ENV_FILE}"
    set +a
  fi
  trust_accessd_server_cert
  nohup "${TARGET_BIN}" >/tmp/accessd-connector.out 2>/tmp/accessd-connector.err < /dev/null &
}

WAS_RUNNING="0"
if is_connector_running; then
  WAS_RUNNING="1"
  echo "[accessd-connector] Existing connector process detected. Stopping before reinstall..."
  if ! stop_running_connector; then
    echo "[accessd-connector] WARNING: connector process did not stop cleanly; continuing install."
  fi
fi

mkdir -p "${INSTALL_DIR}" "${HELPER_DIR}" "${DESKTOP_DIR}"
install -m 0755 "${SOURCE_BIN}" "${TARGET_BIN}"
write_trust_refresh_script

cat > "${HANDLER_SCRIPT}" <<'HANDLER'
#!/usr/bin/env bash
set -euo pipefail

CONNECTOR_BIN="${HOME}/.local/bin/accessd-connector"
if [[ ! -x "${CONNECTOR_BIN}" ]]; then
  CONNECTOR_BIN="accessd-connector"
fi

ENV_FILE="${HOME}/.config/accessd/connector.env"
if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # shellcheck disable=SC1090
  . "${ENV_FILE}"
  set +a
fi

CONNECTOR_ADDR="${ACCESSD_CONNECTOR_ADDR:-127.0.0.1:9494}"
TRUST_SCRIPT="${HOME}/.accessd-connector/bin/trust-refresh-linux.sh"
BACKEND_VERIFY_URL="${ACCESSD_CONNECTOR_BACKEND_VERIFY_URL:-}"
if [[ -z "${ACCESSD_CONNECTOR_SECRET:-}" && -z "${BACKEND_VERIFY_URL}" ]]; then
  echo "[accessd-connector] WARNING: token verification not configured (set ACCESSD_CONNECTOR_BACKEND_VERIFY_URL or ACCESSD_CONNECTOR_SECRET)." >&2
fi
if [[ -x "${TRUST_SCRIPT}" ]]; then
  "${TRUST_SCRIPT}" || true
fi

if curl -fsS --max-time 1 "http://${CONNECTOR_ADDR}/version" >/dev/null 2>&1; then
  exit 0
fi

nohup "${CONNECTOR_BIN}" >/tmp/accessd-connector.out 2>/tmp/accessd-connector.err < /dev/null &
HANDLER
chmod 0755 "${HANDLER_SCRIPT}"

cat > "${DESKTOP_FILE}" <<EOF_DESKTOP
[Desktop Entry]
Type=Application
Name=AccessD Connector URL Handler
Comment=AccessD connector protocol bridge
Exec=${HANDLER_SCRIPT} %u
NoDisplay=true
Terminal=false
MimeType=x-scheme-handler/accessd-connector;
Categories=Network;
EOF_DESKTOP

if command -v xdg-mime >/dev/null 2>&1; then
  xdg-mime default accessd-connector.desktop x-scheme-handler/accessd-connector >/dev/null 2>&1 || true
fi
if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database "${DESKTOP_DIR}" >/dev/null 2>&1 || true
fi

dbeaver_detected="$(pick_existing_path "$(command -v dbeaver 2>/dev/null || true)" "$(command -v dbeaver-ce 2>/dev/null || true)" "/usr/share/dbeaver/dbeaver" "/usr/share/dbeaver-ce/dbeaver" "/snap/bin/dbeaver-ce" "/opt/dbeaver/dbeaver" || true)"
filezilla_detected="$(pick_existing_path "$(command -v filezilla 2>/dev/null || true)" "/usr/bin/filezilla" "/snap/bin/filezilla" || true)"
redis_detected="$(pick_existing_path "$(command -v redis-cli 2>/dev/null || true)" "/usr/bin/redis-cli" "/usr/local/bin/redis-cli" || true)"

if ! command -v ssh >/dev/null 2>&1; then
  echo "[accessd-connector] WARNING: OpenSSH client (ssh) not detected. Shell launch will fail until installed."
fi

dbeaver_path="$(prompt_for_path_if_missing "DBeaver" "${dbeaver_detected}")"
filezilla_path="$(prompt_for_path_if_missing "FileZilla" "${filezilla_detected}")"
redis_cli_path="$(prompt_for_path_if_missing "redis-cli" "${redis_detected}")"
terminal_pref="$(choose_terminal_pref)"

write_installer_config "${dbeaver_path}" "${filezilla_path}" "${redis_cli_path}" "${terminal_pref}"
bootstrap_runtime_env_from_server
write_runtime_env_file
if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # shellcheck disable=SC1090
  . "${ENV_FILE}"
  set +a
fi
trust_accessd_server_cert

if [[ "${WAS_RUNNING}" == "1" ]]; then
  echo "[accessd-connector] Restarting connector after reinstall..."
  start_connector
fi

echo "[accessd-connector] Installed binary: ${TARGET_BIN}"
echo "[accessd-connector] Runtime env file: ${ENV_FILE}"
echo "[accessd-connector] Desktop handler: ${DESKTOP_FILE}"
echo "[accessd-connector] Registered URL scheme: accessd-connector://"
echo "[accessd-connector] UI auto-start can now invoke accessd-connector://start"
